// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

type AdoptionAdQueryResult interface {
	IsAdoptionAdQueryResult()
}

type AdoptionAdsQueryResult interface {
	IsAdoptionAdsQueryResult()
}

type AdoptionAgenciesQueryResult interface {
	IsAdoptionAgenciesQueryResult()
}

type AdoptionAgencyQueryResult interface {
	IsAdoptionAgencyQueryResult()
}

type BannersQueryResult interface {
	IsBannersQueryResult()
}

type CheckInCounterQueryResult interface {
	IsCheckInCounterQueryResult()
}

type CheckInCountersQueryResult interface {
	IsCheckInCountersQueryResult()
}

type CheckInRecordQueryResult interface {
	IsCheckInRecordQueryResult()
}

type EventsQueryResult interface {
	IsEventsQueryResult()
}

type JobsResult interface {
	IsJobsResult()
}

type LoginUserResult interface {
	IsLoginUserResult()
}

type PetProfilesQueryResult interface {
	IsPetProfilesQueryResult()
}

type RefreshAccessTokenResult interface {
	IsRefreshAccessTokenResult()
}

type RetailersQueryResult interface {
	IsRetailersQueryResult()
}

type UserProfilesQueryResult interface {
	IsUserProfilesQueryResult()
}

type VoucherOwnershipQueryResult interface {
	IsVoucherOwnershipQueryResult()
}

type VoucherQueryResult interface {
	IsVoucherQueryResult()
}

type VouchersQueryResult interface {
	IsVouchersQueryResult()
}

type ActiveContest struct {
	Contest *Contest `json:"contest"`
}

type AdoptionActivity struct {
	Details   string   `json:"details"`
	PhotoUrls []string `json:"photoUrls"`
}

type AdoptionActivityInput struct {
	Details   string   `json:"details"`
	PhotoUrls []string `json:"photoUrls"`
}

type AdoptionAd struct {
	ID        primitive.ObjectID `json:"id" bson:"_id"`
	AgencyID  primitive.ObjectID `json:"agencyId"`
	PetName   string             `json:"petName"`
	Sex       Sex                `json:"sex"`
	PetAge    string             `json:"petAge"`
	Breed     *SelectionOption   `json:"breed"`
	PhotoUrls []string           `json:"photoUrls"`
	Remarks   string             `json:"remarks"`
	CreatedAt primitive.DateTime `json:"createdAt"`
	UpdatedAt primitive.DateTime `json:"updatedAt"`
	Hidden    bool               `json:"hidden"`
	Adopted   bool               `json:"adopted"`
}

func (AdoptionAd) IsAdoptionAdQueryResult() {}

type AdoptionAds struct {
	TotalCount int           `json:"totalCount"`
	Items      []*AdoptionAd `json:"items"`
}

func (AdoptionAds) IsAdoptionAdsQueryResult() {}

type AdoptionAdsInput struct {
	AgencyID primitive.ObjectID    `json:"agencyId"`
	Breed    *SelectionOptionInput `json:"breed"`
}

type AdoptionAgencies struct {
	TotalCount int               `json:"totalCount"`
	Items      []*AdoptionAgency `json:"items"`
}

func (AdoptionAgencies) IsAdoptionAgenciesQueryResult() {}

type AdoptionAgenciesInput struct {
	PageNumber           int                   `json:"pageNumber"`
	PageSize             int                   `json:"pageSize"`
	DatetimeFilter       *DatetimeFilter       `json:"datetimeFilter"`
	TerritoriesFilter    *TerritoriesFilter    `json:"territoriesFilter"`
	RecommendationFilter *RecommendationFilter `json:"recommendationFilter"`
	ApprovalFilter       ApprovalFilter        `json:"approvalFilter"`
	UserID               primitive.ObjectID    `json:"userId"`
}

type AdoptionAgency struct {
	ID             primitive.ObjectID     `json:"id" bson:"_id"`
	UserID         primitive.ObjectID     `json:"userId"`
	Name           string                 `json:"name"`
	AvatarURL      string                 `json:"avatarUrl"`
	Phone          string                 `json:"phone"`
	Address        string                 `json:"address"`
	GeoLocation    *GeoLocation           `json:"geoLocation"`
	WebsiteURL     string                 `json:"websiteUrl"`
	PhotoUrls      []string               `json:"photoUrls"`
	Introduction   string                 `json:"introduction"`
	Activity       *AdoptionActivity      `json:"activity"`
	DonationMethod *DonationMethod        `json:"donationMethod"`
	CreatedAt      primitive.DateTime     `json:"createdAt"`
	UpdatedAt      primitive.DateTime     `json:"updatedAt"`
	Ads            AdoptionAdsQueryResult `json:"ads"`
	Approved       bool                   `json:"approved"`
}

func (AdoptionAgency) IsAdoptionAgencyQueryResult() {}

type AppVersionInfo struct {
	LatestReleasedVersion  string `json:"latestReleasedVersion"`
	LowestSupportedVersion string `json:"lowestSupportedVersion"`
	DetailsUrl             string `json:"detailsUrl"`
}

type Banner struct {
	ID            primitive.ObjectID `json:"id" bson:"_id"`
	Name          string             `json:"name"`
	ImageURL      string             `json:"imageUrl"`
	PopupImageURL string             `json:"popupImageUrl"`
	AppPage       AppPage            `json:"appPage"`
	PageParams    string             `json:"pageParams"`
	Visible       bool               `json:"visible"`
}

type Banners struct {
	TotalCount int       `json:"totalCount"`
	Items      []*Banner `json:"items"`
}

func (Banners) IsBannersQueryResult() {}

type BannersInput struct {
	Visible *bool `json:"visible"`
}

type BindPhoneOrEmailInput struct {
	PhoneOrEmail     string `json:"phoneOrEmail"`
	VerificationCode string `json:"verificationCode"`
}

type BlockMomentInput struct {
	BlockedUserId string `json:"blockedUserId"`
	Period        int    `json:"period"`
}

type BreedsFilter struct {
	Names []string `json:"names"`
}

type BreedsFilterInput struct {
	Names []string `json:"names"`
}

type CandidateFilter struct {
	EnrollmentStatus int    `json:"enrollment_status"`
	MatchingText     string `json:"matchingText"`
}

type CategoriesFilter struct {
	Categories []*CategoryFilter `json:"categories"`
}

type CategoryFilter struct {
	Option            *SelectionOptionInput   `json:"option"`
	AdditionalOptions []string                `json:"additionalOptions"`
	SubOptions        []*SelectionOptionInput `json:"subOptions"`
}

type CheckInCounter struct {
	ID                    primitive.ObjectID     `json:"id" bson:"_id"`
	ProductID             primitive.ObjectID     `json:"productId"`
	ProductName           string                 `json:"productName"`
	Name                  string                 `json:"name"`
	Greetings             string                 `json:"greetings"`
	QRCodeURL             string                 `json:"qrCodeUrl"`
	Points                int                    `json:"points"`
	CreatedAt             *primitive.DateTime    `json:"createdAt"`
	ValidTo               *primitive.DateTime    `json:"validTo"`
	ValidFrom             *primitive.DateTime    `json:"validFrom"`
	GeoLocationConstraint *GeoLocationConstraint `json:"geoLocationConstraint"`
	Record                *CheckInRecord         `json:"record"`
}

func (CheckInCounter) IsCheckInCounterQueryResult() {}

type CheckInCounters struct {
	TotalCount int               `json:"totalCount"`
	Items      []*CheckInCounter `json:"items"`
}

func (CheckInCounters) IsCheckInCountersQueryResult() {}

type CheckInCountersInput struct {
	PageNumber int `json:"pageNumber"`
	PageSize   int `json:"pageSize"`
}

type CheckInInput struct {
	CounterID   primitive.ObjectID `json:"counterId"`
	GeoLocation *GeoLocationInput  `json:"geoLocation"`
}

type CheckInRecord struct {
	ID          primitive.ObjectID  `json:"id" bson:"_id"`
	UserID      primitive.ObjectID  `json:"userId"`
	ProductID   primitive.ObjectID  `json:"productId"`
	CounterID   primitive.ObjectID  `json:"counterId"`
	GeoLocation *GeoLocation        `json:"geoLocation"`
	CreatedAt   *primitive.DateTime `json:"createdAt"`
}

func (CheckInRecord) IsCheckInRecordQueryResult() {}

type Comment struct {
	Id                     string                  `json:"id" bson:"_id"`
	PetId                  string                  `json:"petId"`
	UserId                 string                  `json:"userId"`
	RetailerUserId         string                  `json:"retailerUserId"`
	Title                  string                  `json:"title"`
	Details                string                  `json:"details"`
	PictureUrls            []string                `json:"pictureUrls"`
	Score                  int                     `json:"score"`
	Status                 int                     `json:"status"`
	Recommended            bool                    `json:"recommended"`
	DatetimeCreated        string                  `json:"datetimeCreated"`
	CommentatorCertificate *CommentatorCertificate `json:"commentatorCertificate"`
	RetailerProfile        *RetailerProfile        `json:"retailerProfile" bson:"retailerprofile"`
}

type CommentRecommendationFilter struct {
	Option int `json:"option"`
}

type CommentScoreFilter struct {
	Option int `json:"option"`
}

type CommentStatusFilter struct {
	Option int `json:"option"`
}

type CommentatorCertificate struct {
	Phone                string             `json:"phone"`
	Name                 string             `json:"name"`
	SnsPlatformName      string             `json:"snsPlatformName"`
	SnsPlatformSelection *SelectionOption   `json:"snsPlatformSelection"`
	AvatarUrl            string             `json:"avatarUrl"`
	Level                int                `json:"level"`
	Status               int                `json:"status"`
	DatetimeCreated      primitive.DateTime `json:"datetimeCreated"`
}

type CommentatorCertificateStatusFilter struct {
	Option int `json:"option"`
}

type CommentatorCertificates struct {
	Certificates []*CommentatorCertificate `json:"certificates"`
	TotalCount   int                       `json:"totalCount"`
}

type CommentatorCertificatesInput struct {
	PageNumber   int                                 `json:"pageNumber"`
	PageSize     int                                 `json:"pageSize"`
	StatusFilter *CommentatorCertificateStatusFilter `json:"statusFilter"`
}

type Comments struct {
	Comments   []*Comment `json:"comments"`
	TotalCount int        `json:"totalCount"`
}

type CommentsInput struct {
	PetId                   string                       `json:"petId"`
	UserId                  string                       `json:"userId"`
	RetailerUserId          string                       `json:"retailerUserId"`
	PageNumber              int                          `json:"pageNumber"`
	PageSize                int                          `json:"pageSize"`
	StatusFilter            *CommentStatusFilter         `json:"statusFilter"`
	ScoreFilter             *CommentScoreFilter          `json:"scoreFilter"`
	RecommendationFilter    *CommentRecommendationFilter `json:"recommendationFilter"`
	MatchingRetailerName    string                       `json:"matchingRetailerName"`
	MatchingCommentatorName string                       `json:"matchingCommentatorName"`
}

type Contest struct {
	Id        string `json:"id"`
	Name      string `json:"name"`
	StartDate string `json:"startDate"`
	EndDate   string `json:"endDate"`
	PosterUrl string `json:"posterUrl"`
	Active    bool   `json:"active"`
}

type ContestCandidate struct {
	Id                 string             `json:"id"`
	UserId             string             `json:"userId"`
	ContestId          string             `json:"contestId"`
	PetId              string             `json:"petId"`
	PetName            string             `json:"petName"`
	PetOwnerName       string             `json:"petOwnerName"`
	PetOwnerPhone      string             `json:"petOwnerPhone"`
	PetPhotoUrl        string             `json:"petPhotoUrl"`
	PetSnsUrl          string             `json:"petSnsUrl"`
	VotingResult       *VotingResult      `json:"votingResult"`
	Enrollment         *ContestEnrollment `json:"enrollment"`
	Sequence           int                `json:"sequence"`
	ExtraNumberOfVotes int                `json:"extraNumberOfVotes"`
	Position           int                `json:"position"`
}

type ContestCandidates struct {
	Candidates []*ContestCandidate `json:"candidates"`
}

type ContestEnrollment struct {
	Status int    `json:"status"`
	Msg    string `json:"msg"`
}

type ContestEnrollmentInput struct {
	Status int    `json:"status"`
	Msg    string `json:"msg"`
}

type Contests struct {
	Contests []*Contest `json:"contests"`
}

type CreateCommentInput struct {
	PetId          string   `json:"petId"`
	UserId         string   `json:"userId"`
	RetailerUserId string   `json:"retailerUserId"`
	Title          string   `json:"title"`
	Details        string   `json:"details"`
	PictureUrls    []string `json:"pictureUrls"`
	Score          int      `json:"score"`
}

type CreateCommentatorCertificateInput struct {
	UserId               string                `json:"userId"`
	PetId                string                `json:"petId"`
	Phone                string                `json:"phone"`
	Name                 string                `json:"name"`
	SnsPlatformName      string                `json:"snsPlatformName"`
	SnsPlatformSelection *SelectionOptionInput `json:"snsPlatformSelection"`
	AvatarUrl            string                `json:"avatarUrl"`
}

type CreatePetBodyMeasurementsInput struct {
	PetID  primitive.ObjectID `json:"petId"`
	Weight float64            `json:"weight"`
	Back   float64            `json:"back"`
	Chest  float64            `json:"chest"`
	Neck   float64            `json:"neck"`
	Waist  *float64           `json:"waist" bson:",omitempty"`
}

type CreatePetInsuranceInput struct {
	PetID              primitive.ObjectID `json:"petId"`
	CompanyName        string             `json:"companyName"`
	AdvisorPhoneNumber string             `json:"advisorPhoneNumber"`
	EffectiveFrom      primitive.DateTime `json:"effectiveFrom"`
	ValidTo            primitive.DateTime `json:"validTo"`
	NotifiedDaysAhead  int                `json:"notifiedDaysAhead"`
	NotificationOn     bool               `json:"notificationOn"`
}

type CreatePetPawMeasurementsInput struct {
	PetID          primitive.ObjectID `json:"petId"`
	Width          float64            `json:"width"`
	Length         float64            `json:"length"`
	ShoulderHeight *float64           `json:"shoulderHeight" bson:",omitempty"`
	BackLegHeight  *float64           `json:"backLegHeight" bson:",omitempty"`
}

type CreatePetProfileInput struct {
	UserID             string             `json:"userId"`
	AvatarURL          string             `json:"avatarUrl"`
	IDPhotoURL         string             `json:"idPhotoUrl"`
	IDCardURL          string             `json:"idCardUrl"`
	IDCardBgRmdURL     *string            `json:"idCardBgRmdUrl"`
	Name               string             `json:"name"`
	NameZh             string             `json:"nameZh"`
	NameEn             string             `json:"nameEn"`
	Birthday           string             `json:"birthday" bson:",omitempty"`
	Birthday2          primitive.DateTime `json:"birthday2" bson:",omitempty"`
	DepartureDate      primitive.DateTime `json:"departureDate"`
	BreedName          string             `json:"breedName"`
	PetOwnerSnsAccount string             `json:"petOwnerSnsAccount"`
	Sex                string             `json:"sex"`
	HomeArrivalDate    string             `json:"homeArrivalDate"`
}

type CreatePetVaxInput struct {
	PetID               primitive.ObjectID `json:"petId"`
	VaxName             string             `json:"vaxName"`
	Clinic              string             `json:"clinic"`
	VaxxedDate          primitive.DateTime `json:"vaxxedDate"`
	ImmunityLastingUtil primitive.DateTime `json:"immunityLastingUtil"`
	NotifiedDaysAhead   int                `json:"notifiedDaysAhead"`
	NotificationOn      bool               `json:"notificationOn"`
}

type CreateRetailerProfileInput struct {
	AvatarUrl        string                  `json:"avatarUrl" bson:",omitempty"`
	Name             string                  `json:"name" bson:",omitempty"`
	Phone            string                  `json:"phone" bson:",omitempty"`
	GeoLocation      *GeoLocationInput       `json:"geoLocation" bson:",omitempty"`
	ShopPhotoUrls    []string                `json:"shopPhotoUrls" bson:",omitempty"`
	ShopPhotos       []*PhotoInput           `json:"shopPhotos" bson:",omitempty"`
	ShopIntro        string                  `json:"shopIntro" bson:",omitempty"`
	City             *SelectionOptionInput   `json:"city" bson:",omitempty"`
	Region           *SelectionOptionInput   `json:"region" bson:",omitempty"`
	District         *SelectionOptionInput   `json:"district" bson:",omitempty"`
	Landmark         *SelectionOptionInput   `json:"landmark" bson:",omitempty"`
	Address          string                  `json:"address" bson:",omitempty"`
	PaymentMethods   []*SelectionOptionInput `json:"paymentMethods" bson:",omitempty"`
	Category         *SelectionOptionInput   `json:"category" bson:",omitempty"`
	CategoryOptions  []*SelectionOptionInput `json:"categoryOptions" bson:",omitempty"`
	SortingOption    *SelectionOptionInput   `json:"sortingOption" bson:",omitempty"`
	Promotions       string                  `json:"promotions"`
	OpeningHours     string                  `json:"openingHours"`
	Routes           string                  `json:"routes" bson:",omitempty"`
	WebsiteUrl       string                  `json:"websiteUrl" bson:",omitempty"`
	FacebookAccount  string                  `json:"facebookAccount" bson:",omitempty"`
	InstagramAccount string                  `json:"instagramAccount" bson:",omitempty"`
	BusinessLicense  *string                 `json:"businessLicense" bson:",omitempty"`
}

type CreateVoucherOwnershipInput struct {
	VoucherID primitive.ObjectID `json:"voucherId"`
}

type DatesFilter struct {
	Before primitive.DateTime `json:"before"`
	After  primitive.DateTime `json:"after"`
}

type DatesFilterInput struct {
	Before primitive.DateTime `json:"before"`
	After  primitive.DateTime `json:"after"`
}

type DatetimeFilter struct {
	StartedAt primitive.DateTime `json:"startedAt"`
	EndedAt   primitive.DateTime `json:"endedAt"`
}

type DeleteFcmRegistrationTokenInput struct {
	UserId primitive.ObjectID `json:"userId"`
	Uuid   string             `json:"uuid"`
	Token  string             `json:"token"`
}

type DeletePetBodyMeasurementsInput struct {
	ID    primitive.ObjectID `json:"id"`
	PetID primitive.ObjectID `json:"petId"`
}

type DeletePetInsuranceInput struct {
	ID    primitive.ObjectID `json:"id"`
	PetID primitive.ObjectID `json:"petId"`
}

type DeletePetPawMeasurementsInput struct {
	ID    primitive.ObjectID `json:"id"`
	PetID primitive.ObjectID `json:"petId"`
}

type DeletePetVaxInput struct {
	ID    primitive.ObjectID `json:"id"`
	PetID primitive.ObjectID `json:"petId"`
}

type DonationMethod struct {
	Details   string   `json:"details"`
	PhotoUrls []string `json:"photoUrls"`
}

type DonationMethodInput struct {
	Details   string   `json:"details"`
	PhotoUrls []string `json:"photoUrls"`
}

type EditorialPost struct {
	Title        string `json:"title"`
	ThumbnailUrl string `json:"thumbnailUrl"`
	Categories   []int  `json:"categories"`
	Link         string `json:"link"`
	Id           string `json:"id"`
	Guid         string `json:"guid"`
}

type EditorialPosts struct {
	Posts []*EditorialPost `json:"posts"`
}

type Event struct {
	ID                primitive.ObjectID `json:"id" bson:"_id"`
	UserID            primitive.ObjectID `json:"userId"`
	Name              string             `json:"name"`
	StartedAt         primitive.DateTime `json:"startedAt"`
	EndedAt           primitive.DateTime `json:"endedAt"`
	OpeningHours      string             `json:"openingHours"`
	CreatedAt         primitive.DateTime `json:"createdAt"`
	UpdatedAt         primitive.DateTime `json:"updatedAt"`
	Fees              string             `json:"fees"`
	PhoneNumber       string             `json:"phoneNumber"`
	WebsiteUrl        string             `json:"websiteUrl"`
	FacebookAccount   string             `json:"facebookAccount"`
	InstagramAccount  string             `json:"instagramAccount"`
	Category          *SelectionOption   `json:"category"`
	Online            bool               `json:"online"`
	Address           string             `json:"address"`
	Region            *SelectionOption   `json:"region"`
	District          *SelectionOption   `json:"district"`
	GeoLocation       *GeoLocation       `json:"geoLocation"`
	Photos            []*Photo           `json:"photos"`
	Summary           string             `json:"summary"`
	Details           string             `json:"details"`
	Favorited         bool               `json:"favorited"`
	FavoritingUserIds []string           `json:"favoritingUserIds"`
	Recommended       bool               `json:"recommended"`
	Approved          bool               `json:"approved"`
}

type Events struct {
	TotalCount int      `json:"totalCount"`
	Events     []*Event `json:"events"`
}

func (Events) IsEventsQueryResult() {}

type EventsInput struct {
	PageNumber           int                   `json:"pageNumber"`
	PageSize             int                   `json:"pageSize"`
	CategoriesFilter     *CategoriesFilter     `json:"categoriesFilter"`
	DatetimeFilter       *DatetimeFilter       `json:"datetimeFilter"`
	TerritoriesFilter    *TerritoriesFilter    `json:"territoriesFilter"`
	RecommendationFilter *RecommendationFilter `json:"recommendationFilter"`
	ApprovalFilter       ApprovalFilter        `json:"approvalFilter"`
}

type FavoriteFilter struct {
	Option int `json:"option"`
}

type FavoriteRetailerInput struct {
	UserId         string `json:"userId"`
	RetailerUserId string `json:"retailerUserId"`
	Action         int    `json:"action"`
}

type FcmRegistrationToken struct {
	Token     string             `json:"token"`
	Uuid      string             `json:"uuid"`
	UpdatedAt primitive.DateTime `json:"updatedAt"`
}

type FcmRegistrationTokenFilter struct {
	Present bool `json:"present"`
}

type FileOperation struct {
	UploadUrl   string `json:"uploadUrl"`
	DownloadUrl string `json:"downloadUrl"`
}

type FileOperationInput struct {
	Filename   string `json:"filename"`
	PublicRead bool   `json:"publicRead"`
}

type GeoFilter struct {
	Distance    int               `json:"distance"`
	GeoLocation *GeoLocationInput `json:"geoLocation"`
}

type GeoLocation struct {
	Long float64 `json:"long"`
	Lat  float64 `json:"lat"`
}

type GeoLocationConstraint struct {
	GeoLocation      *GeoLocation `json:"geoLocation"`
	FarthestDistance int          `json:"farthestDistance"`
}

type GeoLocationConstraintInput struct {
	GeoLocation      *GeoLocationInput `json:"geoLocation"`
	FarthestDistance int               `json:"farthestDistance"`
}

type GeoLocationInput struct {
	Long float64 `json:"long"`
	Lat  float64 `json:"lat"`
}

type HomepagePosts struct {
	ChannelPosts       []*EditorialPost `json:"channelPosts"`
	InformationalPosts []*EditorialPost `json:"informationalPosts"`
	RetailerAdPosts    []*EditorialPost `json:"retailerAdPosts"`
	SlidingAdPosts     []*EditorialPost `json:"slidingAdPosts"`
	ActivityPosts      []*EditorialPost `json:"activityPosts"`
}

type Job struct {
	Id           primitive.ObjectID `json:"id" bson:"_id"`
	Name         string             `json:"name"`
	Type         JobType            `json:"type"`
	Schedule     *Schedule          `json:"schedule"`
	Message      *Message           `json:"message"`
	Activated    bool               `json:"activated"`
	EntryID      int                `json:"entryId"`
	CreatedAt    primitive.DateTime `json:"createdAt"`
	UpdatedAt    primitive.DateTime `json:"updatedAt"`
	ExecutedAt   primitive.DateTime `json:"executedAt"`
	UsersFilters *UsersFilters      `json:"usersFilters"`
	PetsFilters  *PetsFilters       `json:"petsFilters"`
	Logs         string             `json:"logs"`
}

type JobActivationFilter struct {
	Option bool `json:"option"`
}

type JobTypeFilter struct {
	Option JobType `json:"option"`
}

type Jobs struct {
	TotalCount int    `json:"totalCount"`
	Jobs       []*Job `json:"jobs"`
}

func (Jobs) IsJobsResult() {}

type JobsInput struct {
	PageNumber          int                  `json:"pageNumber"`
	PageSize            int                  `json:"pageSize"`
	JobTypeFilter       *JobTypeFilter       `json:"jobTypeFilter"`
	JobActivationFilter *JobActivationFilter `json:"jobActivationFilter"`
}

type LandmarkFilter struct {
	Option *SelectionOptionInput `json:"option"`
}

type LandmarksFilter struct {
	Landmarks []*LandmarkFilter `json:"landmarks"`
}

type LevelFilter struct {
	Options []int `json:"options"`
}

type Message struct {
	Title      string   `json:"title"`
	Body       string   `json:"body"`
	AppPage    *AppPage `json:"appPage"`
	PageParams string   `json:"pageParams"`
}

type MessageInput struct {
	Title      string   `json:"title"`
	Body       string   `json:"body"`
	ImageURL   string   `json:"imageUrl"`
	AppPage    *AppPage `json:"appPage"`
	PageParams string   `json:"pageParams"`
}

type MigrateCommentsInput struct {
	SrcPetID   primitive.ObjectID   `json:"srcPetId"`
	DstPetID   primitive.ObjectID   `json:"dstPetId"`
	CommentIds []primitive.ObjectID `json:"commentIds"`
}

type Moment struct {
	Id                string           `json:"id" bson:"_id"`
	UserId            string           `json:"userId"`
	Title             string           `json:"title"`
	Link              string           `json:"link"`
	MediaUrl          string           `json:"mediaUrl"`
	MediaThumbnailUrl string           `json:"mediaThumbnailUrl"`
	IsTemplate        bool             `json:"isTemplate"`
	IsVideo           bool             `json:"isVideo"`
	DatetimeCreated   string           `json:"datetimeCreated"`
	CreateDatetime    string           `json:"createDatetime"`
	RetailerProfile   *RetailerProfile `json:"retailerProfile"`
}

type Moments struct {
	Moments []*Moment `json:"moments"`
}

type MomentsReported struct {
	MomentIds []string `json:"momentIds"`
}

type NewContest struct {
	Name      string `json:"name"`
	StartDate string `json:"startDate"`
	EndDate   string `json:"endDate"`
	PosterUrl string `json:"posterUrl"`
	Active    bool   `json:"active"`
}

type NewContestCandidate struct {
	ContestId     string `json:"contestId"`
	PetId         string `json:"petId"`
	PetName       string `json:"petName"`
	PetOwnerName  string `json:"petOwnerName"`
	PetOwnerPhone string `json:"petOwnerPhone"`
	PetPhotoUrl   string `json:"petPhotoUrl"`
	PetSnsUrl     string `json:"petSnsUrl"`
}

type NewMoment struct {
	Title      string `json:"title"`
	Link       string `json:"link"`
	MediaUrl   string `json:"mediaUrl"`
	IsTemplate bool   `json:"isTemplate"`
	IsVideo    bool   `json:"isVideo"`
}

type NewTask struct {
	Name         string             `json:"name"`
	PictureUrl   string             `json:"pictureUrl"`
	DetailsUrl   string             `json:"detailsUrl"`
	StartDate    string             `json:"startDate"`
	EndDate      string             `json:"endDate"`
	Type         int                `json:"type"`
	ShareContent *ShareContentInput `json:"shareContent"`
}

type NewUser struct {
	PhoneOrEmail     string `json:"phoneOrEmail"`
	Password         string `json:"password"`
	VerificationCode string `json:"verificationCode"`
	Name             string `json:"name"`
	ReferralCode     string `json:"referralCode"`
	ReferralUserId   string `json:"referralUserId"`
}

type NewUserWithAppleBinding struct {
	PhoneOrEmail     string `json:"phoneOrEmail"`
	Password         string `json:"password"`
	VerificationCode string `json:"verificationCode"`
	Name             string `json:"name"`
	AuthCode         string `json:"authCode"`
}

type OtherFilter struct {
	Option int `json:"option"`
}

type PetBodyMeasurements struct {
	ID              primitive.ObjectID `json:"id"`
	DatetimeCreated primitive.DateTime `json:"datetimeCreated"`
	Weight          float64            `json:"weight"`
	Back            float64            `json:"back"`
	Chest           float64            `json:"chest"`
	Neck            float64            `json:"neck"`
	Waist           float64            `json:"waist"`
}

type PetInsurance struct {
	ID                 primitive.ObjectID `json:"id"`
	CompanyName        string             `json:"companyName"`
	AdvisorPhoneNumber string             `json:"advisorPhoneNumber"`
	EffectiveFrom      primitive.DateTime `json:"effectiveFrom"`
	ValidTo            primitive.DateTime `json:"validTo"`
	NotifiedDaysAhead  int                `json:"notifiedDaysAhead"`
	NotificationOn     bool               `json:"notificationOn"`
}

type PetPawMeasurements struct {
	ID              primitive.ObjectID `json:"id"`
	DatetimeCreated primitive.DateTime `json:"datetimeCreated"`
	Width           float64            `json:"width"`
	Length          float64            `json:"length"`
	ShoulderHeight  float64            `json:"shoulderHeight"`
	BackLegHeight   float64            `json:"backLegHeight"`
}

type PetProfile struct {
	ID                     string                  `json:"id" bson:"_id"`
	AvatarURL              string                  `json:"avatarUrl"`
	IDPhotoURL             string                  `json:"idPhotoUrl"`
	IDCardURL              string                  `json:"idCardUrl"`
	IDCardBgRmdURL         string                  `json:"idCardBgRmdUrl"`
	IDCardNumber           int                     `json:"idCardNumber"`
	Name                   string                  `json:"name"`
	NameZh                 string                  `json:"nameZh"`
	NameEn                 string                  `json:"nameEn"`
	Birthday               string                  `json:"birthday"`
	Birthday2              primitive.DateTime      `json:"birthday2"`
	DepartureDate          primitive.DateTime      `json:"departureDate"`
	BreedName              string                  `json:"breedName"`
	PetOwnerSnsAccount     string                  `json:"petOwnerSnsAccount"`
	UserID                 string                  `json:"userId"`
	User                   *UserProfile            `json:"user"`
	Sex                    string                  `json:"sex"`
	HomeArrivalDate        string                  `json:"homeArrivalDate"`
	CommentatorCertificate *CommentatorCertificate `json:"commentatorCertificate"`
	CertificateUrls        []string                `json:"certificateUrls"`
	BodyMeasurementsList   []*PetBodyMeasurements  `json:"bodyMeasurementsList"`
	PawMeasurementsList    []*PetPawMeasurements   `json:"pawMeasurementsList"`
	Insurances             []*PetInsurance         `json:"insurances"`
	Vaxes                  []*PetVax               `json:"vaxes"`
	Comments               []*Comment              `json:"comments"`
}

type PetProfiles struct {
	Profiles   []*PetProfile `json:"profiles"`
	TotalCount int           `json:"totalCount"`
}

func (PetProfiles) IsPetProfilesQueryResult() {}

type PetVax struct {
	ID                  primitive.ObjectID `json:"id"`
	VaxName             string             `json:"vaxName"`
	Clinic              string             `json:"clinic"`
	VaxxedDate          primitive.DateTime `json:"vaxxedDate"`
	ImmunityLastingUtil primitive.DateTime `json:"immunityLastingUtil"`
	NotifiedDaysAhead   int                `json:"notifiedDaysAhead"`
	NotificationOn      bool               `json:"notificationOn"`
}

type PetsFilters struct {
	IdCardNumber   int           `json:"idCardNumber"`
	BirthdayFilter *DatesFilter  `json:"birthdayFilter"`
	BreedsFilter   *BreedsFilter `json:"breedsFilter"`
	SexesFilter    *SexesFilter  `json:"sexesFilter"`
}

type PetsFiltersInput struct {
	IdCardNumber   int                `json:"idCardNumber"`
	BirthdayFilter *DatesFilterInput  `json:"birthdayFilter"`
	BreedsFilter   *BreedsFilterInput `json:"breedsFilter"`
	SexesFilter    *SexesFilterInput  `json:"sexesFilter"`
}

type PetsInput struct {
	UserID                             string                              `json:"userId"`
	PageNumber                         int                                 `json:"pageNumber"`
	PageSize                           int                                 `json:"pageSize"`
	MatchingText                       string                              `json:"matchingText"`
	CommentatorCertificateStatusFilter *CommentatorCertificateStatusFilter `json:"commentatorCertificateStatusFilter"`
	IDCardNumber                       int                                 `json:"idCardNumber"`
	BirthdayFilter                     *DatesFilterInput                   `json:"birthdayFilter"`
	BreedsFilter                       *BreedsFilterInput                  `json:"breedsFilter"`
	SexesFilter                        *SexesFilterInput                   `json:"sexesFilter"`
}

type PetsWithCommentsInput struct {
	PageNumber         int               `json:"pageNumber"`
	PageSize           int               `json:"pageSize"`
	CommentDatesFilter *DatesFilterInput `json:"commentDatesFilter"`
}

type Photo struct {
	ID          primitive.ObjectID `json:"id"`
	Url         string             `json:"url"`
	Description string             `json:"description"`
}

type PhotoInput struct {
	Url         string `json:"url"`
	Description string `json:"description"`
}

type RankingFilter struct {
	Option int `json:"option"`
}

type RecommendationFilter struct {
	Option int `json:"option"`
}

type ReportMomentInput struct {
	MomentId       string `json:"momentId"`
	ReportedUserId string `json:"reportedUserId"`
	Reason         string `json:"reason"`
}

type RetailerNameEntries struct {
	Entries []*RetailerNameEntry `json:"entries"`
}

type RetailerNameEntriesInput struct {
	PageSize          int                `json:"pageSize"`
	PageNumber        int                `json:"pageNumber"`
	StartUserId       string             `json:"startUserId"`
	MatchingName      string             `json:"matchingName"`
	MatchingAddress   string             `json:"matchingAddress"`
	TerritoriesFilter *TerritoriesFilter `json:"territoriesFilter"`
	LandmarksFilter   *LandmarksFilter   `json:"landmarksFilter"`
}

type RetailerNameEntry struct {
	Name   string `json:"name"`
	UserId string `json:"userId"`
}

type RetailerProfile struct {
	Id                 string             `json:"id" bson:"_id"`
	UserId             string             `json:"userId"`
	Account            string             `json:"account"`
	Role               int                `json:"role"`
	Level              int                `json:"level"`
	AvatarUrl          string             `json:"avatarUrl"`
	Name               string             `json:"name"`
	Phone              string             `json:"phone"`
	GeoLocation        *GeoLocation       `json:"geoLocation"`
	ShopPhotoUrls      []string           `json:"shopPhotoUrls"`
	ShopPhotos         []*Photo           `json:"shopPhotos"`
	ShopIntro          string             `json:"shopIntro"`
	City               *SelectionOption   `json:"city"`
	Region             *SelectionOption   `json:"region"`
	District           *SelectionOption   `json:"district"`
	Landmark           *SelectionOption   `json:"landmark"`
	Address            string             `json:"address"`
	Moments            []*Moment          `json:"moments"`
	PaymentMethods     []*SelectionOption `json:"paymentMethods"`
	Category           *SelectionOption   `json:"category"`
	RawData            string             `json:"rawData"`
	CategoryOptions    []*SelectionOption `json:"categoryOptions"`
	SortingOption      *SelectionOption   `json:"sortingOption"`
	DatetimeModified   string             `json:"datetimeModified"`
	CalculatedDistance float64            `json:"calculatedDistance"`
	Favorited          bool               `json:"favorited" bson:"favorited,omitempty"`
	FavoritingUserIds  []string           `json:"favoritingUserIds"`
	Promotions         string             `json:"promotions"`
	OpeningHours       string             `json:"openingHours"`
	Routes             string             `json:"routes"`
	WebsiteUrl         string             `json:"websiteUrl"`
	FacebookAccount    string             `json:"facebookAccount"`
	InstagramAccount   string             `json:"instagramAccount"`
	Recommended        bool               `json:"recommended"`
	Rating             float64            `json:"rating"`
	CreatedBy          *UserProfile       `json:"createdBy"`
	CreatedAt          primitive.DateTime `json:"createdAt"`
	BusinessLicense    string             `json:"businessLicense"`
}

type RetailerProfiles struct {
	TotalCount int                `json:"totalCount"`
	Profiles   []*RetailerProfile `json:"profiles"`
}

func (RetailerProfiles) IsRetailersQueryResult() {}

type RetailersBlocked struct {
	UserIds []string `json:"userIds"`
}

type RetailersInput struct {
	UserId               string                `json:"userId"`
	PageSize             int                   `json:"pageSize"`
	PageNumber           int                   `json:"pageNumber"`
	StartUserId          string                `json:"startUserId"`
	MatchingAddress      string                `json:"matchingAddress"`
	MatchingName         string                `json:"matchingName"`
	MatchingPhoneOrEmail string                `json:"matchingPhoneOrEmail"`
	TerritoriesFilter    *TerritoriesFilter    `json:"territoriesFilter"`
	LandmarksFilter      *LandmarksFilter      `json:"landmarksFilter"`
	CategoriesFilter     *CategoriesFilter     `json:"categoriesFilter"`
	GeoFilter            *GeoFilter            `json:"geoFilter"`
	TimeFilter           *TimeFilter           `json:"timeFilter"`
	RoleFilter           *RoleFilter           `json:"roleFilter"`
	LevelFilter          *LevelFilter          `json:"levelFilter"`
	RecommendationFilter *RecommendationFilter `json:"recommendationFilter"`
	FavoriteFilter       *FavoriteFilter       `json:"favoriteFilter"`
	RankingFilter        *RankingFilter        `json:"rankingFilter"`
}

type RoleFilter struct {
	Option int `json:"option"`
}

type Schedule struct {
	Day      int  `json:"day"`
	Hour     int  `json:"hour"`
	Minute   int  `json:"minute"`
	Repeated bool `json:"repeated"`
}

type ScheduleInput struct {
	Day      int  `json:"day"`
	Hour     int  `json:"hour"`
	Minute   int  `json:"minute"`
	Repeated bool `json:"repeated"`
}

type SelectionOption struct {
	Id      string             `json:"id"`
	Name    string             `json:"name"`
	Options []*SelectionOption `json:"options"`
}

type SelectionOptionInput struct {
	Id      string                  `json:"id"`
	Name    string                  `json:"name"`
	Options []*SelectionOptionInput `json:"options"`
}

type SendMessageInput struct {
	Message      *MessageInput      `json:"message"`
	PetsFilters  *PetsFiltersInput  `json:"petsFilters"`
	UsersFilters *UsersFiltersInput `json:"usersFilters"`
	WetRun       bool               `json:"wetRun"`
	JobID        primitive.ObjectID `json:"jobId"`
}

type ServiceError struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

func (ServiceError) IsAdoptionAdQueryResult() {}

func (ServiceError) IsAdoptionAdsQueryResult() {}

func (ServiceError) IsAdoptionAgenciesQueryResult() {}

func (ServiceError) IsCheckInCounterQueryResult() {}

func (ServiceError) IsCheckInCountersQueryResult() {}

func (ServiceError) IsCheckInRecordQueryResult() {}

func (ServiceError) IsEventsQueryResult() {}

func (ServiceError) IsJobsResult() {}

func (ServiceError) IsBannersQueryResult() {}

func (ServiceError) IsPetProfilesQueryResult() {}

func (ServiceError) IsRefreshAccessTokenResult() {}

func (ServiceError) IsRetailersQueryResult() {}

func (ServiceError) IsLoginUserResult() {}

func (ServiceError) IsAdoptionAgencyQueryResult() {}

func (ServiceError) IsUserProfilesQueryResult() {}

func (ServiceError) IsVoucherQueryResult() {}

func (ServiceError) IsVouchersQueryResult() {}

func (ServiceError) IsVoucherOwnershipQueryResult() {}

type SexesFilter struct {
	Names []string `json:"names"`
}

type SexesFilterInput struct {
	Names []string `json:"names"`
}

type ShareContent struct {
	Text       string `json:"text"`
	ImageUrl   string `json:"imageUrl"`
	WebpageUrl string `json:"webpageUrl"`
}

type ShareContentInput struct {
	Text       string `json:"text"`
	ImageUrl   string `json:"imageUrl"`
	WebpageUrl string `json:"webpageUrl"`
}

type Task struct {
	Id            string             `json:"id" bson:"_id"`
	Name          string             `json:"name"`
	PictureUrl    string             `json:"pictureUrl"`
	DetailsUrl    string             `json:"detailsUrl"`
	RedemptionUrl string             `json:"redemptionUrl"`
	StartDate     string             `json:"startDate"`
	EndDate       string             `json:"endDate"`
	Type          int                `json:"type"`
	Status        int                `json:"status"`
	ShareContent  *ShareContent      `json:"shareContent"`
	Participation *TaskParticipation `json:"participation"`
}

type TaskFilter struct {
	Status int `json:"status"`
}

type TaskParticipation struct {
	Id                           string `json:"id" bson:"_id"`
	UserId                       string `json:"userId"`
	TaskId                       string `json:"taskId"`
	Status                       int    `json:"status"`
	RedemptionCode               string `json:"redemptionCode"`
	DatetimeCreated              string `json:"datetimeCreated"`
	DatetimeAchieved             string `json:"datetimeAchieved"`
	DatetimeRedeemed             string `json:"datetimeRedeemed"`
	RedemptionConfirmationUserId string `json:"redemptionConfirmationUserId"`
}

type TaskParticipationFilter struct {
	Status int `json:"status"`
}

type TaskParticipationList struct {
	List []*TaskParticipation `json:"list"`
}

type TaskParticipationListInput struct {
	PageSize                 int                      `json:"pageSize"`
	PageNumber               int                      `json:"pageNumber"`
	UserId                   string                   `json:"userId"`
	StartTaskParticipationId string                   `json:"startTaskParticipationId"`
	Filter                   *TaskParticipationFilter `json:"filter"`
}

type Tasks struct {
	Tasks []*Task `json:"tasks"`
}

type TasksInput struct {
	PageSize            int                      `json:"pageSize"`
	PageNumber          int                      `json:"pageNumber"`
	StartTaskId         string                   `json:"startTaskId"`
	TaskFilter          *TaskFilter              `json:"taskFilter"`
	ParticipationFilter *TaskParticipationFilter `json:"participationFilter"`
}

type TerritoriesFilter struct {
	Territories []*TerritoryFilter `json:"territories"`
}

type TerritoryFilter struct {
	City     *SelectionOptionInput `json:"city"`
	Region   *SelectionOptionInput `json:"region"`
	District *SelectionOptionInput `json:"district"`
}

type TimeFilter struct {
	Option int `json:"option"`
}

type UpdateAdoptionAd struct {
	AgencyID  *primitive.ObjectID   `json:"agencyId" bson:",omitempty"`
	PetName   *string               `json:"petName" bson:",omitempty"`
	Sex       *Sex                  `json:"sex" bson:",omitempty"`
	PetAge    *string               `json:"petAge" bson:",omitempty"`
	Breed     *SelectionOptionInput `json:"breed" bson:",omitempty"`
	PhotoUrls []string              `json:"photoUrls" bson:",omitempty"`
	Remarks   *string               `json:"remarks" bson:",omitempty"`
	Hidden    *bool                 `json:"hidden" bson:",omitempty"`
	Adopted   *bool                 `json:"adopted" bson:",omitempty"`
}

type UpdateAdoptionAdInput struct {
	ID primitive.ObjectID `json:"id" bson:"_id"`
	Ad *UpdateAdoptionAd  `json:"ad"`
}

type UpdateAdoptionAgency struct {
	UserID         *primitive.ObjectID    `json:"userId" bson:",omitempty"`
	Name           *string                `json:"name" bson:",omitempty"`
	AvatarURL      *string                `json:"avatarUrl" bson:",omitempty"`
	Phone          *string                `json:"phone" bson:",omitempty"`
	Address        *string                `json:"address" bson:",omitempty"`
	GeoLocation    *GeoLocationInput      `json:"geoLocation" bson:",omitempty"`
	WebsiteURL     *string                `json:"websiteUrl" bson:",omitempty"`
	PhotoUrls      []string               `json:"photoUrls" bson:",omitempty"`
	Introduction   *string                `json:"introduction" bson:",omitempty"`
	Activity       *AdoptionActivityInput `json:"activity" bson:",omitempty"`
	DonationMethod *DonationMethodInput   `json:"donationMethod" bson:",omitempty"`
	Approved       *bool                  `json:"approved" bson:",omitempty"`
}

type UpdateAdoptionAgencyInput struct {
	ID     primitive.ObjectID    `json:"id" bson:"_id"`
	Agency *UpdateAdoptionAgency `json:"agency"`
}

type UpdateBanner struct {
	Name          *string  `json:"name" bson:",omitempty"`
	ImageURL      *string  `json:"imageUrl" bson:",omitempty"`
	PopupImageURL *string  `json:"popupImageUrl" bson:",omitempty"`
	AppPage       *AppPage `json:"appPage" bson:",omitempty"`
	PageParams    *string  `json:"pageParams" bson:",omitempty"`
	Visible       *bool    `json:"visible" bson:",omitempty"`
}

type UpdateBannerInput struct {
	ID     primitive.ObjectID `json:"id"`
	Banner *UpdateBanner      `json:"banner"`
}

type UpdateCheckInCounter struct {
	Name                  *string                     `json:"name" bson:",omitempty"`
	Greetings             *string                     `json:"greetings" bson:",omitempty"`
	ProductID             *primitive.ObjectID         `json:"productId" bson:",omitempty"`
	ProductName           *string                     `json:"productName" bson:",omitempty"`
	QRCodeURL             *string                     `json:"qrCodeUrl" bson:",omitempty"`
	Points                *int                        `json:"points" bson:",omitempty"`
	ValidTo               *primitive.DateTime         `json:"validTo" bson:",omitempty"`
	ValidFrom             *primitive.DateTime         `json:"validFrom" bson:",omitempty"`
	GeoLocationConstraint *GeoLocationConstraintInput `json:"geoLocationConstraint" bson:",omitempty"`
}

type UpdateCheckInCounterInput struct {
	ID      primitive.ObjectID    `json:"id"`
	Counter *UpdateCheckInCounter `json:"counter"`
}

type UpdateCommentStatusInput struct {
	Id     string `json:"id"`
	Status int    `json:"status"`
}

type UpdateCommentatorCertificateInput struct {
	PetId  string `json:"petId"`
	Status int    `json:"status"`
	Level  int    `json:"level"`
}

type UpdateContest struct {
	Id        string `json:"id"`
	Name      string `json:"name"`
	StartDate string `json:"startDate"`
	EndDate   string `json:"endDate"`
	PosterUrl string `json:"posterUrl"`
	Active    bool   `json:"active"`
}

type UpdateContestCandidate struct {
	Id          string `json:"id"`
	PetName     string `json:"petName"`
	PetPhotoUrl string `json:"petPhotoUrl"`
	PetSnsUrl   string `json:"petSnsUrl"`
	Sequence    int    `json:"sequence"`
}

type UpdateContestCandidateEnrollment struct {
	Id         string                  `json:"id"`
	Enrollment *ContestEnrollmentInput `json:"enrollment"`
}

type UpdateContestCandidateExtraNumberOfVotes struct {
	Id                 string `json:"id"`
	ExtraNumberOfVotes int    `json:"extraNumberOfVotes"`
}

type UpdateEventApprovalInput struct {
	EventID primitive.ObjectID               `json:"eventId"`
	Payload *UpdateEventApprovalInputPayload `json:"payload"`
}

type UpdateEventApprovalInputPayload struct {
	Approved bool `json:"approved"`
}

type UpdateEventInput struct {
	ID      primitive.ObjectID       `json:"id"`
	Payload *UpdateEventInputPayload `json:"payload"`
}

type UpdateEventInputPayload struct {
	UserID            primitive.ObjectID    `json:"userId"`
	Name              string                `json:"name"`
	StartedAt         primitive.DateTime    `json:"startedAt"`
	EndedAt           primitive.DateTime    `json:"endedAt"`
	OpeningHours      string                `json:"openingHours"`
	Fees              string                `json:"fees"`
	PhoneNumber       string                `json:"phoneNumber"`
	WebsiteUrl        string                `json:"websiteUrl"`
	FacebookAccount   string                `json:"facebookAccount"`
	InstagramAccount  string                `json:"instagramAccount"`
	Category          *SelectionOptionInput `json:"category"`
	Online            bool                  `json:"online"`
	Address           string                `json:"address"`
	Region            *SelectionOptionInput `json:"region"`
	District          *SelectionOptionInput `json:"district"`
	GeoLocation       *GeoLocationInput     `json:"geoLocation"`
	Photos            []*PhotoInput         `json:"photos"`
	Summary           string                `json:"summary"`
	Details           string                `json:"details"`
	Favorited         bool                  `json:"favorited"`
	FavoritingUserIds []string              `json:"favoritingUserIds"`
}

type UpdateEventRecommendationInput struct {
	EventID primitive.ObjectID                     `json:"eventId"`
	Payload *UpdateEventRecommendationInputPayload `json:"payload"`
}

type UpdateEventRecommendationInputPayload struct {
	Recommended bool `json:"recommended"`
}

type UpdateJobActivationInput struct {
	JobId   primitive.ObjectID          `json:"jobId"`
	Payload *UpdateJobActivationPayload `json:"payload"`
}

type UpdateJobActivationPayload struct {
	Activated bool `json:"activated"`
}

type UpdateJobEntryIDInput struct {
	JobId   primitive.ObjectID       `json:"jobId"`
	Payload *UpdateJobEntryIDPayload `json:"payload"`
}

type UpdateJobEntryIDPayload struct {
	EntryID int `json:"entryId"`
}

type UpdateJobInput struct {
	Id      primitive.ObjectID `json:"id"`
	Payload *UpdateJobPayload  `json:"payload"`
}

type UpdateJobPayload struct {
	Name         string             `json:"name" bson:",omitempty"`
	Type         *JobType           `json:"type" bson:",omitempty"`
	Schedule     *ScheduleInput     `json:"schedule" bson:",omitempty"`
	Message      *MessageInput      `json:"message" bson:",omitempty"`
	UsersFilters *UsersFiltersInput `json:"usersFilters"`
	PetsFilters  *PetsFiltersInput  `json:"petsFilters"`
}

type UpdateMoment struct {
	Id         string `json:"id"`
	Title      string `json:"title"`
	Link       string `json:"link"`
	MediaUrl   string `json:"mediaUrl"`
	IsTemplate bool   `json:"isTemplate"`
}

type UpdatePetCertificatesInput struct {
	PetID primitive.ObjectID `json:"petId"`
	Urls  []string           `json:"urls"`
}

type UpdatePetProfileInput struct {
	ID                 string             `json:"id"`
	AvatarURL          string             `json:"avatarUrl" bson:",omitempty"`
	IDPhotoURL         string             `json:"idPhotoUrl" bson:",omitempty"`
	IDCardURL          string             `json:"idCardUrl" bson:",omitempty"`
	IDCardBgRmdURL     *string            `json:"idCardBgRmdUrl" bson:",omitempty"`
	Name               string             `json:"name"`
	NameZh             string             `json:"nameZh" bson:",omitempty"`
	NameEn             string             `json:"nameEn" bson:",omitempty"`
	Birthday           string             `json:"birthday" bson:",omitempty"`
	Birthday2          primitive.DateTime `json:"birthday2" bson:",omitempty"`
	DepartureDate      primitive.DateTime `json:"departureDate" bson:",omitempty"`
	BreedName          string             `json:"breedName" bson:",omitempty"`
	PetOwnerSnsAccount string             `json:"petOwnerSnsAccount" bson:",omitempty"`
	Sex                string             `json:"sex" bson:",omitempty"`
	HomeArrivalDate    string             `json:"homeArrivalDate" bson:",omitempty"`
}

type UpdateRetailerProfileInput struct {
	UserId  string                      `json:"userId"`
	Profile *CreateRetailerProfileInput `json:"profile"`
}

type UpdateRetailerRatingInput struct {
	UserId primitive.ObjectID `json:"userId"`
	Rating float64            `json:"rating"`
}

type UpdateRetailerRecommendationInput struct {
	UserId      primitive.ObjectID `json:"userId"`
	Recommended bool               `json:"recommended"`
}

type UpdateTask struct {
	Id           string             `json:"id"`
	Name         string             `json:"name"`
	PictureUrl   string             `json:"pictureUrl"`
	DetailsUrl   string             `json:"detailsUrl"`
	StartDate    string             `json:"startDate"`
	EndDate      string             `json:"endDate"`
	Type         int                `json:"type"`
	ShareContent *ShareContentInput `json:"shareContent"`
}

type UpdateTaskParticipation struct {
	TaskId string `json:"taskId"`
}

type UpdateTaskParticipationStatusInput struct {
	TaskID         primitive.ObjectID `json:"taskId"`
	RedemptionCode string             `json:"redemptionCode"`
	Status         int                `json:"status"`
}

type UpdateTaskStatusInput struct {
	TaskId primitive.ObjectID `json:"taskId"`
	Status int                `json:"status"`
}

type UpdateUserBasics struct {
	Name                   string `json:"name"`
	FamilyName             string `json:"familyName"`
	GivenName              string `json:"givenName"`
	ProfileBackgroundImage string `json:"profileBackgroundImage"`
}

type UpdateUserLevel struct {
	UserId string `json:"userId"`
	Level  int    `json:"level"`
}

type UpdateUserPointsInput struct {
	UserID primitive.ObjectID `json:"userId"`
	Points int                `json:"points"`
}

type UpdateUserRoleInput struct {
	UserId string `json:"userId"`
	Role   int    `json:"role"`
}

type UpdateVoucher struct {
	RedemptionPoint   *int                `json:"redemptionPoint" bson:",omitempty"`
	Name              *string             `json:"name" bson:",omitempty"`
	Description       *string             `json:"description" bson:",omitempty"`
	Terms             *string             `json:"terms" bson:",omitempty"`
	ValidFrom         *primitive.DateTime `json:"validFrom" bson:",omitempty"`
	ValidTo           *primitive.DateTime `json:"validTo" bson:",omitempty"`
	ImageURL          *string             `json:"imageUrl" bson:",omitempty"`
	RetailerAvatarURL *string             `json:"retailerAvatarUrl" bson:",omitempty"`
}

type UpdateVoucherInput struct {
	ID      primitive.ObjectID `json:"id"`
	Voucher *UpdateVoucher     `json:"voucher"`
}

type UpdateVoucherOwnershipStatusInput struct {
	RedemptionCode string        `json:"redemptionCode"`
	Status         VoucherStatus `json:"status"`
}

type UserAuthentication struct {
	UserId       primitive.ObjectID `json:"userId"`
	AccessToken  string             `json:"accessToken"`
	RefreshToken string             `json:"refreshToken"`
	ErrCode      int                `json:"errCode"`
	Msg          string             `json:"msg"`
}

func (UserAuthentication) IsRefreshAccessTokenResult() {}

func (UserAuthentication) IsLoginUserResult() {}

type UserCountInput struct {
	MatchingText         string       `json:"matchingText"`
	MatchingPhoneOrEmail string       `json:"matchingPhoneOrEmail"`
	RoleFilter           *RoleFilter  `json:"roleFilter"`
	LevelFilter          *LevelFilter `json:"levelFilter"`
}

type UserCredentials struct {
	PhoneOrEmail string `json:"phoneOrEmail"`
	Password     string `json:"password"`
}

type UserProfile struct {
	Id                     primitive.ObjectID        `json:"id" bson:"_id"`
	Name                   string                    `json:"name"`
	Phone                  string                    `json:"phone"`
	Email                  string                    `json:"email"`
	Role                   int                       `json:"role"`
	Level                  int                       `json:"level"`
	Points                 int                       `json:"points"`
	RetailerProfile        *RetailerProfile          `json:"retailerProfile"`
	AvatarUrl              string                    `json:"avatarUrl"`
	FamilyName             string                    `json:"familyName"`
	GivenName              string                    `json:"givenName"`
	ReferralUserId         string                    `json:"referralUserId"`
	DatetimeCreated        string                    `json:"datetimeCreated"`
	FcmRegistrationToken   string                    `json:"fcmRegistrationToken"`
	FcmRegistrationTokens  []*FcmRegistrationToken   `json:"fcmRegistrationTokens"`
	AppleUserId            string                    `json:"appleUserId"`
	GoogleUserId           string                    `json:"googleUserId"`
	FacebookId             string                    `json:"facebookUserId"`
	Deactivated            bool                      `json:"deactivated"`
	ProfileBackgroundImage string                    `json:"profileBackgroundImage"`
	AdoptionAgency         AdoptionAgencyQueryResult `json:"adoptionAgency"`
}

type UserProfileWithPassword struct {
	Id          primitive.ObjectID `json:"id" bson:"_id"`
	Password    string             `json:"password"`
	Role        int                `json:"role"`
	Level       int                `json:"level"`
	Deactivated bool               `json:"deactivated"`
}

type UserProfiles struct {
	TotalCount int            `json:"totalCount"`
	Profiles   []*UserProfile `json:"profiles"`
}

func (UserProfiles) IsUserProfilesQueryResult() {}

type UserProfilesInput struct {
	LastId                     string                      `json:"lastId"`
	PageSize                   int                         `json:"pageSize"`
	PageNumber                 int                         `json:"pageNumber"`
	RoleFilter                 *RoleFilter                 `json:"roleFilter"`
	FcmRegistrationTokenFilter *FcmRegistrationTokenFilter `json:"fcmRegistrationTokenFilter"`
	MatchingPhoneOrEmail       string                      `json:"matchingPhoneOrEmail"`
}

type UsersFilters struct {
	MatchingPhoneOrEmail string `json:"matchingPhoneOrEmail"`
}

type UsersFiltersInput struct {
	MatchingPhoneOrEmail string `json:"matchingPhoneOrEmail"`
}

type VerificationCodeGenerationResult struct {
	ErrCode int    `json:"errCode"`
	Msg     string `json:"msg"`
}

type VoteForCandidate struct {
	CandidateId string `json:"candidateId"`
}

type VotingResult struct {
	NumberOfVotes int  `json:"numberOfVotes"`
	Voted         bool `json:"voted"`
}

type Voucher struct {
	ID                primitive.ObjectID  `json:"id" bson:"_id"`
	RedemptionPoint   int                 `json:"redemptionPoint"`
	CreatedAt         *primitive.DateTime `json:"createdAt"`
	Name              string              `json:"name"`
	Terms             string              `json:"terms"`
	Description       string              `json:"description"`
	ValidFrom         *primitive.DateTime `json:"validFrom"`
	ValidTo           *primitive.DateTime `json:"validTo"`
	ImageURL          string              `json:"imageUrl"`
	RetailerAvatarURL string              `json:"retailerAvatarUrl"`
	Ownership         *VoucherOwnership   `json:"ownership"`
}

func (Voucher) IsVoucherQueryResult() {}

type VoucherOwnership struct {
	ID                           string              `json:"id" bson:"_id"`
	UserID                       primitive.ObjectID  `json:"userId"`
	VoucherID                    primitive.ObjectID  `json:"voucherId"`
	Status                       VoucherStatus       `json:"status"`
	RedemptionCode               string              `json:"redemptionCode"`
	CreatedAt                    *primitive.DateTime `json:"createdAt"`
	RedeemedAt                   *primitive.DateTime `json:"redeemedAt"`
	RedemptionConfirmationUserID *primitive.ObjectID `json:"redemptionConfirmationUserId"`
}

func (VoucherOwnership) IsVoucherOwnershipQueryResult() {}

type Vouchers struct {
	TotalCount int        `json:"totalCount"`
	Items      []*Voucher `json:"items"`
}

func (Vouchers) IsVouchersQueryResult() {}

type VouchersInput struct {
	PageNumber int `json:"pageNumber"`
	PageSize   int `json:"pageSize"`
}

type VouchersWithOwnershipInput struct {
	PageNumber    int            `json:"pageNumber"`
	PageSize      int            `json:"pageSize"`
	VoucherStatus *VoucherStatus `json:"voucherStatus"`
}

type AppPage string

const (
	AppPageEditorialPost   AppPage = "EDITORIAL_POST"
	AppPageRetailerDetails AppPage = "RETAILER_DETAILS"
	AppPageRetailerList    AppPage = "RETAILER_LIST"
	AppPageEventDetails    AppPage = "EVENT_DETAILS"
	AppPageContestDetails  AppPage = "CONTEST_DETAILS"
)

var AllAppPage = []AppPage{
	AppPageEditorialPost,
	AppPageRetailerDetails,
	AppPageRetailerList,
	AppPageEventDetails,
	AppPageContestDetails,
}

func (e AppPage) IsValid() bool {
	switch e {
	case AppPageEditorialPost, AppPageRetailerDetails, AppPageRetailerList, AppPageEventDetails, AppPageContestDetails:
		return true
	}
	return false
}

func (e AppPage) String() string {
	return string(e)
}

func (e *AppPage) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AppPage(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AppPage", str)
	}
	return nil
}

func (e AppPage) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type ApprovalFilter string

const (
	ApprovalFilterApproved   ApprovalFilter = "APPROVED"
	ApprovalFilterUnapproved ApprovalFilter = "UNAPPROVED"
	ApprovalFilterAny        ApprovalFilter = "ANY"
)

var AllApprovalFilter = []ApprovalFilter{
	ApprovalFilterApproved,
	ApprovalFilterUnapproved,
	ApprovalFilterAny,
}

func (e ApprovalFilter) IsValid() bool {
	switch e {
	case ApprovalFilterApproved, ApprovalFilterUnapproved, ApprovalFilterAny:
		return true
	}
	return false
}

func (e ApprovalFilter) String() string {
	return string(e)
}

func (e *ApprovalFilter) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ApprovalFilter(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ApprovalFilter", str)
	}
	return nil
}

func (e ApprovalFilter) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type JobType string

const (
	JobTypePetBirthdayWishesNotification JobType = "PET_BIRTHDAY_WISHES_NOTIFICATION"
	JobTypeCampaignNotification          JobType = "CAMPAIGN_NOTIFICATION"
)

var AllJobType = []JobType{
	JobTypePetBirthdayWishesNotification,
	JobTypeCampaignNotification,
}

func (e JobType) IsValid() bool {
	switch e {
	case JobTypePetBirthdayWishesNotification, JobTypeCampaignNotification:
		return true
	}
	return false
}

func (e JobType) String() string {
	return string(e)
}

func (e *JobType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = JobType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid JobType", str)
	}
	return nil
}

func (e JobType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Sex string

const (
	SexF Sex = "F"
	SexM Sex = "M"
)

var AllSex = []Sex{
	SexF,
	SexM,
}

func (e Sex) IsValid() bool {
	switch e {
	case SexF, SexM:
		return true
	}
	return false
}

func (e Sex) String() string {
	return string(e)
}

func (e *Sex) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Sex(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Sex", str)
	}
	return nil
}

func (e Sex) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type VoucherStatus string

const (
	VoucherStatusRedeemable VoucherStatus = "REDEEMABLE"
	VoucherStatusRedeemed   VoucherStatus = "REDEEMED"
	VoucherStatusExpired    VoucherStatus = "EXPIRED"
	VoucherStatusInvalid    VoucherStatus = "INVALID"
)

var AllVoucherStatus = []VoucherStatus{
	VoucherStatusRedeemable,
	VoucherStatusRedeemed,
	VoucherStatusExpired,
	VoucherStatusInvalid,
}

func (e VoucherStatus) IsValid() bool {
	switch e {
	case VoucherStatusRedeemable, VoucherStatusRedeemed, VoucherStatusExpired, VoucherStatusInvalid:
		return true
	}
	return false
}

func (e VoucherStatus) String() string {
	return string(e)
}

func (e *VoucherStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = VoucherStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid VoucherStatus", str)
	}
	return nil
}

func (e VoucherStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
