// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: moment/moment.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MomentReported struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReportedUserId  string `protobuf:"bytes,1,opt,name=reported_user_id,json=reportedUserId,proto3" json:"reported_user_id,omitempty"`
	UserId          string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MomentId        string `protobuf:"bytes,3,opt,name=moment_id,json=momentId,proto3" json:"moment_id,omitempty"`
	Reason          string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	DatetimeCreated string `protobuf:"bytes,5,opt,name=datetime_created,json=datetimeCreated,proto3" json:"datetime_created,omitempty"`
}

func (x *MomentReported) Reset() {
	*x = MomentReported{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moment_moment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MomentReported) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MomentReported) ProtoMessage() {}

func (x *MomentReported) ProtoReflect() protoreflect.Message {
	mi := &file_moment_moment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MomentReported.ProtoReflect.Descriptor instead.
func (*MomentReported) Descriptor() ([]byte, []int) {
	return file_moment_moment_proto_rawDescGZIP(), []int{0}
}

func (x *MomentReported) GetReportedUserId() string {
	if x != nil {
		return x.ReportedUserId
	}
	return ""
}

func (x *MomentReported) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MomentReported) GetMomentId() string {
	if x != nil {
		return x.MomentId
	}
	return ""
}

func (x *MomentReported) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *MomentReported) GetDatetimeCreated() string {
	if x != nil {
		return x.DatetimeCreated
	}
	return ""
}

type RetailerBlocked struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockedUserId   string `protobuf:"bytes,1,opt,name=blocked_user_id,json=blockedUserId,proto3" json:"blocked_user_id,omitempty"`
	UserId          string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Period          int32  `protobuf:"varint,3,opt,name=period,proto3" json:"period,omitempty"`
	DatetimeCreated string `protobuf:"bytes,4,opt,name=datetime_created,json=datetimeCreated,proto3" json:"datetime_created,omitempty"`
}

func (x *RetailerBlocked) Reset() {
	*x = RetailerBlocked{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moment_moment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetailerBlocked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetailerBlocked) ProtoMessage() {}

func (x *RetailerBlocked) ProtoReflect() protoreflect.Message {
	mi := &file_moment_moment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetailerBlocked.ProtoReflect.Descriptor instead.
func (*RetailerBlocked) Descriptor() ([]byte, []int) {
	return file_moment_moment_proto_rawDescGZIP(), []int{1}
}

func (x *RetailerBlocked) GetBlockedUserId() string {
	if x != nil {
		return x.BlockedUserId
	}
	return ""
}

func (x *RetailerBlocked) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RetailerBlocked) GetPeriod() int32 {
	if x != nil {
		return x.Period
	}
	return 0
}

func (x *RetailerBlocked) GetDatetimeCreated() string {
	if x != nil {
		return x.DatetimeCreated
	}
	return ""
}

type Moment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title           string           `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Link            string           `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	MediaUrl        string           `protobuf:"bytes,3,opt,name=media_url,json=mediaUrl,proto3" json:"media_url,omitempty"`
	UserId          string           `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsTemplate      bool             `protobuf:"varint,5,opt,name=is_template,json=isTemplate,proto3" json:"is_template,omitempty"`
	Id              string           `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	IsVideo         bool             `protobuf:"varint,7,opt,name=is_video,json=isVideo,proto3" json:"is_video,omitempty"`
	DatetimeCreated string           `protobuf:"bytes,8,opt,name=datetime_created,json=datetimeCreated,proto3" json:"datetime_created,omitempty"`
	RetailerProfile *RetailerProfile `protobuf:"bytes,9,opt,name=retailer_profile,json=retailerProfile,proto3" json:"retailer_profile,omitempty"`
	CreateDatetime  string           `protobuf:"bytes,10,opt,name=create_datetime,json=createDatetime,proto3" json:"create_datetime,omitempty"`
}

func (x *Moment) Reset() {
	*x = Moment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moment_moment_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Moment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Moment) ProtoMessage() {}

func (x *Moment) ProtoReflect() protoreflect.Message {
	mi := &file_moment_moment_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Moment.ProtoReflect.Descriptor instead.
func (*Moment) Descriptor() ([]byte, []int) {
	return file_moment_moment_proto_rawDescGZIP(), []int{2}
}

func (x *Moment) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Moment) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Moment) GetMediaUrl() string {
	if x != nil {
		return x.MediaUrl
	}
	return ""
}

func (x *Moment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Moment) GetIsTemplate() bool {
	if x != nil {
		return x.IsTemplate
	}
	return false
}

func (x *Moment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Moment) GetIsVideo() bool {
	if x != nil {
		return x.IsVideo
	}
	return false
}

func (x *Moment) GetDatetimeCreated() string {
	if x != nil {
		return x.DatetimeCreated
	}
	return ""
}

func (x *Moment) GetRetailerProfile() *RetailerProfile {
	if x != nil {
		return x.RetailerProfile
	}
	return nil
}

func (x *Moment) GetCreateDatetime() string {
	if x != nil {
		return x.CreateDatetime
	}
	return ""
}

type SelectionOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *SelectionOption) Reset() {
	*x = SelectionOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moment_moment_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectionOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectionOption) ProtoMessage() {}

func (x *SelectionOption) ProtoReflect() protoreflect.Message {
	mi := &file_moment_moment_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectionOption.ProtoReflect.Descriptor instead.
func (*SelectionOption) Descriptor() ([]byte, []int) {
	return file_moment_moment_proto_rawDescGZIP(), []int{3}
}

func (x *SelectionOption) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SelectionOption) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RetailerProfile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AvatarUrl      string             `protobuf:"bytes,1,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Name           string             `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone          string             `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	GeoLocation    *GeoLocation       `protobuf:"bytes,4,opt,name=geo_location,json=geoLocation,proto3" json:"geo_location,omitempty"`
	ShopPhotoUrls  []string           `protobuf:"bytes,5,rep,name=shop_photo_urls,json=shopPhotoUrls,proto3" json:"shop_photo_urls,omitempty"`
	ShopIntro      string             `protobuf:"bytes,6,opt,name=shop_intro,json=shopIntro,proto3" json:"shop_intro,omitempty"`
	Address        string             `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	PaymentMethods []*SelectionOption `protobuf:"bytes,8,rep,name=payment_methods,json=paymentMethods,proto3" json:"payment_methods,omitempty"`
	Category       *SelectionOption   `protobuf:"bytes,9,opt,name=category,proto3" json:"category,omitempty"`
	City           *SelectionOption   `protobuf:"bytes,10,opt,name=city,proto3" json:"city,omitempty"`
	Region         *SelectionOption   `protobuf:"bytes,11,opt,name=region,proto3" json:"region,omitempty"`
	District       *SelectionOption   `protobuf:"bytes,12,opt,name=district,proto3" json:"district,omitempty"`
	RawData        string             `protobuf:"bytes,13,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	Account        string             `protobuf:"bytes,14,opt,name=account,proto3" json:"account,omitempty"`
	UserId         string             `protobuf:"bytes,15,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Level          int32              `protobuf:"varint,16,opt,name=level,proto3" json:"level,omitempty"`
	Moments        []*Moment          `protobuf:"bytes,17,rep,name=moments,proto3" json:"moments,omitempty"`
}

func (x *RetailerProfile) Reset() {
	*x = RetailerProfile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moment_moment_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetailerProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetailerProfile) ProtoMessage() {}

func (x *RetailerProfile) ProtoReflect() protoreflect.Message {
	mi := &file_moment_moment_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetailerProfile.ProtoReflect.Descriptor instead.
func (*RetailerProfile) Descriptor() ([]byte, []int) {
	return file_moment_moment_proto_rawDescGZIP(), []int{4}
}

func (x *RetailerProfile) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *RetailerProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RetailerProfile) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RetailerProfile) GetGeoLocation() *GeoLocation {
	if x != nil {
		return x.GeoLocation
	}
	return nil
}

func (x *RetailerProfile) GetShopPhotoUrls() []string {
	if x != nil {
		return x.ShopPhotoUrls
	}
	return nil
}

func (x *RetailerProfile) GetShopIntro() string {
	if x != nil {
		return x.ShopIntro
	}
	return ""
}

func (x *RetailerProfile) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RetailerProfile) GetPaymentMethods() []*SelectionOption {
	if x != nil {
		return x.PaymentMethods
	}
	return nil
}

func (x *RetailerProfile) GetCategory() *SelectionOption {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *RetailerProfile) GetCity() *SelectionOption {
	if x != nil {
		return x.City
	}
	return nil
}

func (x *RetailerProfile) GetRegion() *SelectionOption {
	if x != nil {
		return x.Region
	}
	return nil
}

func (x *RetailerProfile) GetDistrict() *SelectionOption {
	if x != nil {
		return x.District
	}
	return nil
}

func (x *RetailerProfile) GetRawData() string {
	if x != nil {
		return x.RawData
	}
	return ""
}

func (x *RetailerProfile) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *RetailerProfile) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RetailerProfile) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *RetailerProfile) GetMoments() []*Moment {
	if x != nil {
		return x.Moments
	}
	return nil
}

type GeoLocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lat  float64 `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Long float64 `protobuf:"fixed64,2,opt,name=long,proto3" json:"long,omitempty"`
}

func (x *GeoLocation) Reset() {
	*x = GeoLocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moment_moment_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeoLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoLocation) ProtoMessage() {}

func (x *GeoLocation) ProtoReflect() protoreflect.Message {
	mi := &file_moment_moment_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoLocation.ProtoReflect.Descriptor instead.
func (*GeoLocation) Descriptor() ([]byte, []int) {
	return file_moment_moment_proto_rawDescGZIP(), []int{5}
}

func (x *GeoLocation) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *GeoLocation) GetLong() float64 {
	if x != nil {
		return x.Long
	}
	return 0
}

type PostMomentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Moment *Moment `protobuf:"bytes,1,opt,name=moment,proto3" json:"moment,omitempty"`
}

func (x *PostMomentRequest) Reset() {
	*x = PostMomentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moment_moment_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostMomentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMomentRequest) ProtoMessage() {}

func (x *PostMomentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moment_moment_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMomentRequest.ProtoReflect.Descriptor instead.
func (*PostMomentRequest) Descriptor() ([]byte, []int) {
	return file_moment_moment_proto_rawDescGZIP(), []int{6}
}

func (x *PostMomentRequest) GetMoment() *Moment {
	if x != nil {
		return x.Moment
	}
	return nil
}

type PostMomentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PostMomentResponse) Reset() {
	*x = PostMomentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moment_moment_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostMomentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMomentResponse) ProtoMessage() {}

func (x *PostMomentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moment_moment_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMomentResponse.ProtoReflect.Descriptor instead.
func (*PostMomentResponse) Descriptor() ([]byte, []int) {
	return file_moment_moment_proto_rawDescGZIP(), []int{7}
}

type GetMomentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetMomentRequest) Reset() {
	*x = GetMomentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moment_moment_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMomentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMomentRequest) ProtoMessage() {}

func (x *GetMomentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moment_moment_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMomentRequest.ProtoReflect.Descriptor instead.
func (*GetMomentRequest) Descriptor() ([]byte, []int) {
	return file_moment_moment_proto_rawDescGZIP(), []int{8}
}

func (x *GetMomentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMomentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Moment *Moment `protobuf:"bytes,1,opt,name=moment,proto3" json:"moment,omitempty"`
}

func (x *GetMomentResponse) Reset() {
	*x = GetMomentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moment_moment_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMomentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMomentResponse) ProtoMessage() {}

func (x *GetMomentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moment_moment_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMomentResponse.ProtoReflect.Descriptor instead.
func (*GetMomentResponse) Descriptor() ([]byte, []int) {
	return file_moment_moment_proto_rawDescGZIP(), []int{9}
}

func (x *GetMomentResponse) GetMoment() *Moment {
	if x != nil {
		return x.Moment
	}
	return nil
}

type GetMomentsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetMomentsRequest) Reset() {
	*x = GetMomentsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moment_moment_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMomentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMomentsRequest) ProtoMessage() {}

func (x *GetMomentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moment_moment_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMomentsRequest.ProtoReflect.Descriptor instead.
func (*GetMomentsRequest) Descriptor() ([]byte, []int) {
	return file_moment_moment_proto_rawDescGZIP(), []int{10}
}

func (x *GetMomentsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetMomentsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Moments []*Moment `protobuf:"bytes,1,rep,name=moments,proto3" json:"moments,omitempty"`
}

func (x *GetMomentsResponse) Reset() {
	*x = GetMomentsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moment_moment_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMomentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMomentsResponse) ProtoMessage() {}

func (x *GetMomentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moment_moment_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMomentsResponse.ProtoReflect.Descriptor instead.
func (*GetMomentsResponse) Descriptor() ([]byte, []int) {
	return file_moment_moment_proto_rawDescGZIP(), []int{11}
}

func (x *GetMomentsResponse) GetMoments() []*Moment {
	if x != nil {
		return x.Moments
	}
	return nil
}

type GetMomentsReportedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetMomentsReportedRequest) Reset() {
	*x = GetMomentsReportedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moment_moment_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMomentsReportedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMomentsReportedRequest) ProtoMessage() {}

func (x *GetMomentsReportedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moment_moment_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMomentsReportedRequest.ProtoReflect.Descriptor instead.
func (*GetMomentsReportedRequest) Descriptor() ([]byte, []int) {
	return file_moment_moment_proto_rawDescGZIP(), []int{12}
}

func (x *GetMomentsReportedRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetMomentsReportedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MomentIds []string `protobuf:"bytes,1,rep,name=moment_ids,json=momentIds,proto3" json:"moment_ids,omitempty"`
}

func (x *GetMomentsReportedResponse) Reset() {
	*x = GetMomentsReportedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moment_moment_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMomentsReportedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMomentsReportedResponse) ProtoMessage() {}

func (x *GetMomentsReportedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moment_moment_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMomentsReportedResponse.ProtoReflect.Descriptor instead.
func (*GetMomentsReportedResponse) Descriptor() ([]byte, []int) {
	return file_moment_moment_proto_rawDescGZIP(), []int{13}
}

func (x *GetMomentsReportedResponse) GetMomentIds() []string {
	if x != nil {
		return x.MomentIds
	}
	return nil
}

type GetRetailersBlockedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetRetailersBlockedRequest) Reset() {
	*x = GetRetailersBlockedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moment_moment_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRetailersBlockedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRetailersBlockedRequest) ProtoMessage() {}

func (x *GetRetailersBlockedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moment_moment_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRetailersBlockedRequest.ProtoReflect.Descriptor instead.
func (*GetRetailersBlockedRequest) Descriptor() ([]byte, []int) {
	return file_moment_moment_proto_rawDescGZIP(), []int{14}
}

func (x *GetRetailersBlockedRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetRetailersBlockedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserIds []string `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
}

func (x *GetRetailersBlockedResponse) Reset() {
	*x = GetRetailersBlockedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moment_moment_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRetailersBlockedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRetailersBlockedResponse) ProtoMessage() {}

func (x *GetRetailersBlockedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moment_moment_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRetailersBlockedResponse.ProtoReflect.Descriptor instead.
func (*GetRetailersBlockedResponse) Descriptor() ([]byte, []int) {
	return file_moment_moment_proto_rawDescGZIP(), []int{15}
}

func (x *GetRetailersBlockedResponse) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type GetRetailersNearbyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string       `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GeoLocation *GeoLocation `protobuf:"bytes,2,opt,name=geo_location,json=geoLocation,proto3" json:"geo_location,omitempty"`
	PageNumber  int32        `protobuf:"varint,3,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	PageSize    int32        `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *GetRetailersNearbyRequest) Reset() {
	*x = GetRetailersNearbyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moment_moment_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRetailersNearbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRetailersNearbyRequest) ProtoMessage() {}

func (x *GetRetailersNearbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moment_moment_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRetailersNearbyRequest.ProtoReflect.Descriptor instead.
func (*GetRetailersNearbyRequest) Descriptor() ([]byte, []int) {
	return file_moment_moment_proto_rawDescGZIP(), []int{16}
}

func (x *GetRetailersNearbyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetRetailersNearbyRequest) GetGeoLocation() *GeoLocation {
	if x != nil {
		return x.GeoLocation
	}
	return nil
}

func (x *GetRetailersNearbyRequest) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *GetRetailersNearbyRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetRetailersNearbyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Profiles []*RetailerProfile `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
}

func (x *GetRetailersNearbyResponse) Reset() {
	*x = GetRetailersNearbyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moment_moment_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRetailersNearbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRetailersNearbyResponse) ProtoMessage() {}

func (x *GetRetailersNearbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moment_moment_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRetailersNearbyResponse.ProtoReflect.Descriptor instead.
func (*GetRetailersNearbyResponse) Descriptor() ([]byte, []int) {
	return file_moment_moment_proto_rawDescGZIP(), []int{17}
}

func (x *GetRetailersNearbyResponse) GetProfiles() []*RetailerProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type PutMomentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Moment *Moment `protobuf:"bytes,1,opt,name=moment,proto3" json:"moment,omitempty"`
}

func (x *PutMomentRequest) Reset() {
	*x = PutMomentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moment_moment_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutMomentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutMomentRequest) ProtoMessage() {}

func (x *PutMomentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moment_moment_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutMomentRequest.ProtoReflect.Descriptor instead.
func (*PutMomentRequest) Descriptor() ([]byte, []int) {
	return file_moment_moment_proto_rawDescGZIP(), []int{18}
}

func (x *PutMomentRequest) GetMoment() *Moment {
	if x != nil {
		return x.Moment
	}
	return nil
}

type PutMomentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PutMomentResponse) Reset() {
	*x = PutMomentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moment_moment_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutMomentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutMomentResponse) ProtoMessage() {}

func (x *PutMomentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moment_moment_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutMomentResponse.ProtoReflect.Descriptor instead.
func (*PutMomentResponse) Descriptor() ([]byte, []int) {
	return file_moment_moment_proto_rawDescGZIP(), []int{19}
}

type DeleteMomentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteMomentRequest) Reset() {
	*x = DeleteMomentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moment_moment_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMomentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMomentRequest) ProtoMessage() {}

func (x *DeleteMomentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moment_moment_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMomentRequest.ProtoReflect.Descriptor instead.
func (*DeleteMomentRequest) Descriptor() ([]byte, []int) {
	return file_moment_moment_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteMomentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteMomentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteMomentResponse) Reset() {
	*x = DeleteMomentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moment_moment_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMomentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMomentResponse) ProtoMessage() {}

func (x *DeleteMomentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moment_moment_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMomentResponse.ProtoReflect.Descriptor instead.
func (*DeleteMomentResponse) Descriptor() ([]byte, []int) {
	return file_moment_moment_proto_rawDescGZIP(), []int{21}
}

type PostMomentReportedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MomentReported *MomentReported `protobuf:"bytes,1,opt,name=moment_reported,json=momentReported,proto3" json:"moment_reported,omitempty"`
}

func (x *PostMomentReportedRequest) Reset() {
	*x = PostMomentReportedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moment_moment_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostMomentReportedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMomentReportedRequest) ProtoMessage() {}

func (x *PostMomentReportedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moment_moment_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMomentReportedRequest.ProtoReflect.Descriptor instead.
func (*PostMomentReportedRequest) Descriptor() ([]byte, []int) {
	return file_moment_moment_proto_rawDescGZIP(), []int{22}
}

func (x *PostMomentReportedRequest) GetMomentReported() *MomentReported {
	if x != nil {
		return x.MomentReported
	}
	return nil
}

type PostMomentReportedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PostMomentReportedResponse) Reset() {
	*x = PostMomentReportedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moment_moment_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostMomentReportedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMomentReportedResponse) ProtoMessage() {}

func (x *PostMomentReportedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moment_moment_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMomentReportedResponse.ProtoReflect.Descriptor instead.
func (*PostMomentReportedResponse) Descriptor() ([]byte, []int) {
	return file_moment_moment_proto_rawDescGZIP(), []int{23}
}

type PostRetailerBlockedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RetailerBlocked *RetailerBlocked `protobuf:"bytes,1,opt,name=retailer_blocked,json=retailerBlocked,proto3" json:"retailer_blocked,omitempty"`
}

func (x *PostRetailerBlockedRequest) Reset() {
	*x = PostRetailerBlockedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moment_moment_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostRetailerBlockedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostRetailerBlockedRequest) ProtoMessage() {}

func (x *PostRetailerBlockedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moment_moment_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostRetailerBlockedRequest.ProtoReflect.Descriptor instead.
func (*PostRetailerBlockedRequest) Descriptor() ([]byte, []int) {
	return file_moment_moment_proto_rawDescGZIP(), []int{24}
}

func (x *PostRetailerBlockedRequest) GetRetailerBlocked() *RetailerBlocked {
	if x != nil {
		return x.RetailerBlocked
	}
	return nil
}

type PostRetailerBlockedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PostRetailerBlockedResponse) Reset() {
	*x = PostRetailerBlockedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moment_moment_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostRetailerBlockedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostRetailerBlockedResponse) ProtoMessage() {}

func (x *PostRetailerBlockedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moment_moment_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostRetailerBlockedResponse.ProtoReflect.Descriptor instead.
func (*PostRetailerBlockedResponse) Descriptor() ([]byte, []int) {
	return file_moment_moment_proto_rawDescGZIP(), []int{25}
}

type DeleteMomentReportedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteMomentReportedRequest) Reset() {
	*x = DeleteMomentReportedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moment_moment_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMomentReportedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMomentReportedRequest) ProtoMessage() {}

func (x *DeleteMomentReportedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moment_moment_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMomentReportedRequest.ProtoReflect.Descriptor instead.
func (*DeleteMomentReportedRequest) Descriptor() ([]byte, []int) {
	return file_moment_moment_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteMomentReportedRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteMomentReportedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteMomentReportedResponse) Reset() {
	*x = DeleteMomentReportedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moment_moment_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMomentReportedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMomentReportedResponse) ProtoMessage() {}

func (x *DeleteMomentReportedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moment_moment_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMomentReportedResponse.ProtoReflect.Descriptor instead.
func (*DeleteMomentReportedResponse) Descriptor() ([]byte, []int) {
	return file_moment_moment_proto_rawDescGZIP(), []int{27}
}

type DeleteRetailerBlockedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockedUserId string `protobuf:"bytes,1,opt,name=blocked_user_id,json=blockedUserId,proto3" json:"blocked_user_id,omitempty"`
	UserId        string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *DeleteRetailerBlockedRequest) Reset() {
	*x = DeleteRetailerBlockedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moment_moment_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRetailerBlockedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRetailerBlockedRequest) ProtoMessage() {}

func (x *DeleteRetailerBlockedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moment_moment_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRetailerBlockedRequest.ProtoReflect.Descriptor instead.
func (*DeleteRetailerBlockedRequest) Descriptor() ([]byte, []int) {
	return file_moment_moment_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteRetailerBlockedRequest) GetBlockedUserId() string {
	if x != nil {
		return x.BlockedUserId
	}
	return ""
}

func (x *DeleteRetailerBlockedRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteRetailerBlockedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteRetailerBlockedResponse) Reset() {
	*x = DeleteRetailerBlockedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moment_moment_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRetailerBlockedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRetailerBlockedResponse) ProtoMessage() {}

func (x *DeleteRetailerBlockedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moment_moment_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRetailerBlockedResponse.ProtoReflect.Descriptor instead.
func (*DeleteRetailerBlockedResponse) Descriptor() ([]byte, []int) {
	return file_moment_moment_proto_rawDescGZIP(), []int{29}
}

var File_moment_moment_proto protoreflect.FileDescriptor

var file_moment_moment_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0xb3, 0x01,
	0x0a, 0x0e, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64,
	0x12, 0x28, 0x0a, 0x10, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x72, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x10, 0x64, 0x61, 0x74, 0x65,
	0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0f, 0x64, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x22, 0x95, 0x01, 0x0a, 0x0f, 0x52, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x65, 0x72,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x65, 0x64, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x69,
	0x6f, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64,
	0x12, 0x29, 0x0a, 0x10, 0x64, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x64, 0x61, 0x74, 0x65,
	0x74, 0x69, 0x6d, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x22, 0xcc, 0x02, 0x0a, 0x06,
	0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b,
	0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x55, 0x72, 0x6c, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x74, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x54,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x76, 0x69,
	0x64, 0x65, 0x6f, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x12, 0x29, 0x0a, 0x10, 0x64, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x64, 0x61,
	0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x42, 0x0a,
	0x10, 0x72, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74,
	0x2e, 0x52, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x52, 0x0f, 0x72, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x65,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x44, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x35, 0x0a, 0x0f, 0x53, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x8b, 0x05, 0x0a, 0x0f, 0x52, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x50, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x5f,
	0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x76, 0x61, 0x74, 0x61,
	0x72, 0x55, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x36,
	0x0a, 0x0c, 0x67, 0x65, 0x6f, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x47, 0x65,
	0x6f, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x67, 0x65, 0x6f, 0x4c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x0f, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x70,
	0x68, 0x6f, 0x74, 0x6f, 0x5f, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0d, 0x73, 0x68, 0x6f, 0x70, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x55, 0x72, 0x6c, 0x73, 0x12, 0x1d,
	0x0a, 0x0a, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x68, 0x6f, 0x70, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x40, 0x0a, 0x0f, 0x70, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0e, 0x70, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x12, 0x33, 0x0a, 0x08, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x6f,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x2b,
	0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d,
	0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x2f, 0x0a, 0x06, 0x72,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x6f,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x33, 0x0a, 0x08,
	0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x61, 0x77, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x0d, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x61, 0x77, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x10, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x28, 0x0a, 0x07, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x11, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22,
	0x33, 0x0a, 0x0b, 0x47, 0x65, 0x6f, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10,
	0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x61, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04,
	0x6c, 0x6f, 0x6e, 0x67, 0x22, 0x3b, 0x0a, 0x11, 0x50, 0x6f, 0x73, 0x74, 0x4d, 0x6f, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x06, 0x6d, 0x6f, 0x6d,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x6f, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x6d, 0x6f, 0x6d, 0x65, 0x6e,
	0x74, 0x22, 0x14, 0x0a, 0x12, 0x50, 0x6f, 0x73, 0x74, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x22, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4d, 0x6f,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3b, 0x0a, 0x11, 0x47,
	0x65, 0x74, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x26, 0x0a, 0x06, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x06, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x2c, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4d,
	0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3e, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x07,
	0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x6d,
	0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x34, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3b, 0x0a, 0x1a,
	0x47, 0x65, 0x74, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x6f,
	0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09,
	0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x73, 0x22, 0x35, 0x0a, 0x1a, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x73, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x22, 0x38, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x73,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x19, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x22, 0xaa, 0x01, 0x0a, 0x19, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x73, 0x4e, 0x65, 0x61, 0x72, 0x62,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x36, 0x0a, 0x0c, 0x67, 0x65, 0x6f, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74,
	0x2e, 0x47, 0x65, 0x6f, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x67, 0x65,
	0x6f, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x61, 0x67,
	0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x70, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61,
	0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70,
	0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x51, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x73, 0x4e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74,
	0x2e, 0x52, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x52, 0x08, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x22, 0x3a, 0x0a, 0x10, 0x50, 0x75,
	0x74, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26,
	0x0a, 0x06, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x06,
	0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x13, 0x0a, 0x11, 0x50, 0x75, 0x74, 0x4d, 0x6f, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x25, 0x0a, 0x13, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x16, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x6f, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x5c, 0x0a, 0x19, 0x50, 0x6f,
	0x73, 0x74, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3f, 0x0a, 0x0f, 0x6d, 0x6f, 0x6d, 0x65, 0x6e,
	0x74, 0x5f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x52, 0x0e, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x22, 0x1c, 0x0a, 0x1a, 0x50, 0x6f, 0x73, 0x74,
	0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x60, 0x0a, 0x1a, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x42, 0x0a, 0x10, 0x72, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x65, 0x72,
	0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x65, 0x72,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x52, 0x0f, 0x72, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x65,
	0x72, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x22, 0x1d, 0x0a, 0x1b, 0x50, 0x6f, 0x73, 0x74,
	0x52, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2d, 0x0a, 0x1b, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1e, 0x0a, 0x1c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x5f, 0x0a, 0x1c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x65,
	0x64, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x1f, 0x0a, 0x1d, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xa0, 0x08, 0x0a, 0x0d, 0x4d, 0x6f, 0x6d,
	0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x45, 0x0a, 0x0a, 0x50, 0x6f,
	0x73, 0x74, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x19, 0x2e, 0x6d, 0x6f, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x6f, 0x73,
	0x74, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x42, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x18,
	0x2e, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6d, 0x6f, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x12, 0x19, 0x2e, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x47, 0x65, 0x74,
	0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5d, 0x0a, 0x12,
	0x47, 0x65, 0x74, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x65, 0x64, 0x12, 0x21, 0x2e, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x4d,
	0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x47,
	0x65, 0x74, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x60, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x73, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x65, 0x64, 0x12, 0x22, 0x2e, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x73, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x73, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5d, 0x0a,
	0x12, 0x47, 0x65, 0x74, 0x52, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x73, 0x4e, 0x65, 0x61,
	0x72, 0x62, 0x79, 0x12, 0x21, 0x2e, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x73, 0x4e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x73, 0x4e, 0x65, 0x61, 0x72,
	0x62, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x09,
	0x50, 0x75, 0x74, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x2e, 0x6d, 0x6f, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x50, 0x75, 0x74, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x75, 0x74,
	0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x4b, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x1b, 0x2e, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e,
	0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x6f, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5d, 0x0a,
	0x12, 0x50, 0x6f, 0x73, 0x74, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x65, 0x64, 0x12, 0x21, 0x2e, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x6f, 0x73,
	0x74, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x50, 0x6f, 0x73, 0x74, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x63, 0x0a, 0x14,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x65, 0x64, 0x12, 0x23, 0x2e, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6d, 0x6f, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x60, 0x0a, 0x13, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x65,
	0x72, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x12, 0x22, 0x2e, 0x6d, 0x6f, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x6d,
	0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x65, 0x72, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x66, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x65, 0x72, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x12, 0x24, 0x2e, 0x6d,
	0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x65, 0x72, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x25, 0x2e, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x65,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_moment_moment_proto_rawDescOnce sync.Once
	file_moment_moment_proto_rawDescData = file_moment_moment_proto_rawDesc
)

func file_moment_moment_proto_rawDescGZIP() []byte {
	file_moment_moment_proto_rawDescOnce.Do(func() {
		file_moment_moment_proto_rawDescData = protoimpl.X.CompressGZIP(file_moment_moment_proto_rawDescData)
	})
	return file_moment_moment_proto_rawDescData
}

var file_moment_moment_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_moment_moment_proto_goTypes = []interface{}{
	(*MomentReported)(nil),                // 0: moment.MomentReported
	(*RetailerBlocked)(nil),               // 1: moment.RetailerBlocked
	(*Moment)(nil),                        // 2: moment.Moment
	(*SelectionOption)(nil),               // 3: moment.SelectionOption
	(*RetailerProfile)(nil),               // 4: moment.RetailerProfile
	(*GeoLocation)(nil),                   // 5: moment.GeoLocation
	(*PostMomentRequest)(nil),             // 6: moment.PostMomentRequest
	(*PostMomentResponse)(nil),            // 7: moment.PostMomentResponse
	(*GetMomentRequest)(nil),              // 8: moment.GetMomentRequest
	(*GetMomentResponse)(nil),             // 9: moment.GetMomentResponse
	(*GetMomentsRequest)(nil),             // 10: moment.GetMomentsRequest
	(*GetMomentsResponse)(nil),            // 11: moment.GetMomentsResponse
	(*GetMomentsReportedRequest)(nil),     // 12: moment.GetMomentsReportedRequest
	(*GetMomentsReportedResponse)(nil),    // 13: moment.GetMomentsReportedResponse
	(*GetRetailersBlockedRequest)(nil),    // 14: moment.GetRetailersBlockedRequest
	(*GetRetailersBlockedResponse)(nil),   // 15: moment.GetRetailersBlockedResponse
	(*GetRetailersNearbyRequest)(nil),     // 16: moment.GetRetailersNearbyRequest
	(*GetRetailersNearbyResponse)(nil),    // 17: moment.GetRetailersNearbyResponse
	(*PutMomentRequest)(nil),              // 18: moment.PutMomentRequest
	(*PutMomentResponse)(nil),             // 19: moment.PutMomentResponse
	(*DeleteMomentRequest)(nil),           // 20: moment.DeleteMomentRequest
	(*DeleteMomentResponse)(nil),          // 21: moment.DeleteMomentResponse
	(*PostMomentReportedRequest)(nil),     // 22: moment.PostMomentReportedRequest
	(*PostMomentReportedResponse)(nil),    // 23: moment.PostMomentReportedResponse
	(*PostRetailerBlockedRequest)(nil),    // 24: moment.PostRetailerBlockedRequest
	(*PostRetailerBlockedResponse)(nil),   // 25: moment.PostRetailerBlockedResponse
	(*DeleteMomentReportedRequest)(nil),   // 26: moment.DeleteMomentReportedRequest
	(*DeleteMomentReportedResponse)(nil),  // 27: moment.DeleteMomentReportedResponse
	(*DeleteRetailerBlockedRequest)(nil),  // 28: moment.DeleteRetailerBlockedRequest
	(*DeleteRetailerBlockedResponse)(nil), // 29: moment.DeleteRetailerBlockedResponse
}
var file_moment_moment_proto_depIdxs = []int32{
	4,  // 0: moment.Moment.retailer_profile:type_name -> moment.RetailerProfile
	5,  // 1: moment.RetailerProfile.geo_location:type_name -> moment.GeoLocation
	3,  // 2: moment.RetailerProfile.payment_methods:type_name -> moment.SelectionOption
	3,  // 3: moment.RetailerProfile.category:type_name -> moment.SelectionOption
	3,  // 4: moment.RetailerProfile.city:type_name -> moment.SelectionOption
	3,  // 5: moment.RetailerProfile.region:type_name -> moment.SelectionOption
	3,  // 6: moment.RetailerProfile.district:type_name -> moment.SelectionOption
	2,  // 7: moment.RetailerProfile.moments:type_name -> moment.Moment
	2,  // 8: moment.PostMomentRequest.moment:type_name -> moment.Moment
	2,  // 9: moment.GetMomentResponse.moment:type_name -> moment.Moment
	2,  // 10: moment.GetMomentsResponse.moments:type_name -> moment.Moment
	5,  // 11: moment.GetRetailersNearbyRequest.geo_location:type_name -> moment.GeoLocation
	4,  // 12: moment.GetRetailersNearbyResponse.profiles:type_name -> moment.RetailerProfile
	2,  // 13: moment.PutMomentRequest.moment:type_name -> moment.Moment
	0,  // 14: moment.PostMomentReportedRequest.moment_reported:type_name -> moment.MomentReported
	1,  // 15: moment.PostRetailerBlockedRequest.retailer_blocked:type_name -> moment.RetailerBlocked
	6,  // 16: moment.MomentService.PostMoment:input_type -> moment.PostMomentRequest
	8,  // 17: moment.MomentService.GetMoment:input_type -> moment.GetMomentRequest
	10, // 18: moment.MomentService.GetMoments:input_type -> moment.GetMomentsRequest
	12, // 19: moment.MomentService.GetMomentsReported:input_type -> moment.GetMomentsReportedRequest
	14, // 20: moment.MomentService.GetRetailersBlocked:input_type -> moment.GetRetailersBlockedRequest
	16, // 21: moment.MomentService.GetRetailersNearby:input_type -> moment.GetRetailersNearbyRequest
	18, // 22: moment.MomentService.PutMoment:input_type -> moment.PutMomentRequest
	20, // 23: moment.MomentService.DeleteMoment:input_type -> moment.DeleteMomentRequest
	22, // 24: moment.MomentService.PostMomentReported:input_type -> moment.PostMomentReportedRequest
	26, // 25: moment.MomentService.DeleteMomentReported:input_type -> moment.DeleteMomentReportedRequest
	24, // 26: moment.MomentService.PostRetailerBlocked:input_type -> moment.PostRetailerBlockedRequest
	28, // 27: moment.MomentService.DeleteRetailerBlocked:input_type -> moment.DeleteRetailerBlockedRequest
	7,  // 28: moment.MomentService.PostMoment:output_type -> moment.PostMomentResponse
	9,  // 29: moment.MomentService.GetMoment:output_type -> moment.GetMomentResponse
	11, // 30: moment.MomentService.GetMoments:output_type -> moment.GetMomentsResponse
	13, // 31: moment.MomentService.GetMomentsReported:output_type -> moment.GetMomentsReportedResponse
	15, // 32: moment.MomentService.GetRetailersBlocked:output_type -> moment.GetRetailersBlockedResponse
	17, // 33: moment.MomentService.GetRetailersNearby:output_type -> moment.GetRetailersNearbyResponse
	19, // 34: moment.MomentService.PutMoment:output_type -> moment.PutMomentResponse
	21, // 35: moment.MomentService.DeleteMoment:output_type -> moment.DeleteMomentResponse
	23, // 36: moment.MomentService.PostMomentReported:output_type -> moment.PostMomentReportedResponse
	27, // 37: moment.MomentService.DeleteMomentReported:output_type -> moment.DeleteMomentReportedResponse
	25, // 38: moment.MomentService.PostRetailerBlocked:output_type -> moment.PostRetailerBlockedResponse
	29, // 39: moment.MomentService.DeleteRetailerBlocked:output_type -> moment.DeleteRetailerBlockedResponse
	28, // [28:40] is the sub-list for method output_type
	16, // [16:28] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_moment_moment_proto_init() }
func file_moment_moment_proto_init() {
	if File_moment_moment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_moment_moment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MomentReported); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_moment_moment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetailerBlocked); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_moment_moment_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Moment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_moment_moment_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectionOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_moment_moment_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetailerProfile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_moment_moment_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeoLocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_moment_moment_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostMomentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_moment_moment_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostMomentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_moment_moment_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMomentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_moment_moment_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMomentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_moment_moment_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMomentsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_moment_moment_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMomentsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_moment_moment_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMomentsReportedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_moment_moment_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMomentsReportedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_moment_moment_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRetailersBlockedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_moment_moment_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRetailersBlockedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_moment_moment_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRetailersNearbyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_moment_moment_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRetailersNearbyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_moment_moment_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutMomentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_moment_moment_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutMomentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_moment_moment_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMomentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_moment_moment_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMomentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_moment_moment_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostMomentReportedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_moment_moment_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostMomentReportedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_moment_moment_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostRetailerBlockedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_moment_moment_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostRetailerBlockedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_moment_moment_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMomentReportedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_moment_moment_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMomentReportedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_moment_moment_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRetailerBlockedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_moment_moment_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRetailerBlockedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_moment_moment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_moment_moment_proto_goTypes,
		DependencyIndexes: file_moment_moment_proto_depIdxs,
		MessageInfos:      file_moment_moment_proto_msgTypes,
	}.Build()
	File_moment_moment_proto = out.File
	file_moment_moment_proto_rawDesc = nil
	file_moment_moment_proto_goTypes = nil
	file_moment_moment_proto_depIdxs = nil
}
